# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Abigail Brady <morwen@evilmagic.org>, Bastien Nocera <hadess@hadess.net>, 2012
# Andi Chandler <andi@gowling.com>, 2013
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
# Andi Chandler <andi@gowling.com>, 2017. #zanata
# Andi Chandler <andi@gowling.com>, 2018. #zanata
# Andi Chandler <andi@gowling.com>, 2019. #zanata
# Andi Chandler <andi@gowling.com>, 2020. #zanata
msgid ""
msgstr ""
"Project-Id-Version: glance VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-19 06:56+0000\n"
"PO-Revision-Date: 2020-06-02 19:31+0000\n"
"Last-Translator: Andi Chandler <Unknown>\n"
"Language-Team: English (United Kingdom)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-07-09 19:26+0000\n"
"X-Generator: Launchpad (build 4809fcb62f445aaa3ae919f7f6c3cc7d156ea57a)\n"
"Language: en_GB\n"
"Generated-By: Babel 2.0\n"

#: glance/location.py:101
msgid "Invalid location"
msgstr "Invalid location"

#: glance/location.py:333
msgid "Invalid locations"
msgstr "Invalid locations"

#: glance/store/__init__.py:667
#, python-format
msgid "Original locations is not empty: %s"
msgstr "Original locations is not empty: %s"

#: glance/location.py:440
msgid "Signature verification failed"
msgstr "Signature verification failed"

#: glance/store/__init__.py:739
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr "Get image %(id)s data failed: %(err)s."

#: glance/notifier.py:239 glance/api/v1/upload_utils.py:184
#: glance/api/v2/image_data.py:107
#, python-format
msgid "Image storage media is full: %s"
msgstr "Image storage media is full: %s"

#: glance/notifier.py:243 glance/api/v1/upload_utils.py:193
#: glance/api/v2/image_data.py:128
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "Insufficient permissions on image storage media: %s"

#: glance/notifier.py:248
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr "Cannot save data for image %(image_id)s: %(error)s"

#: glance/notifier.py:254
#, python-format
msgid ""
"Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""
"Unable to upload duplicate image data for image%(image_id)s: %(error)s"

#: glance/notifier.py:261
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr "Not allowed to upload image data for image %(image_id)s: %(error)s"

#: glance/notifier.py:267
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have been "
"deleted during the upload: %(error)s"
msgstr ""
"Image %(image_id)s could not be found after upload. The image may have been "
"deleted during the upload: %(error)s"

#: glance/notifier.py:274
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"

#: glance/notifier.py:281
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error: "
"%(error)s"
msgstr ""
"Failed to upload image data for image %(image_id)s due to internal error: "
"%(error)s"

#: glance/schema.py:58
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr "custom properties (%(props)s) conflict with base properties"

#: glance/scrubber.py:42 glance/store/__init__.py:58
msgid "The amount of time in seconds to delay before performing a delete."
msgstr "The amount of time in seconds to delay before performing a delete."

#: glance/scrubber.py:40
msgid ""
"The size of thread pool to be used for scrubbing images. The default is one, "
"which signifies serial scrubbing. Any value above one indicates the max "
"number of images that may be scrubbed in parallel."
msgstr ""
"The size of thread pool to be used for scrubbing images. The default is one, "
"which signifies serial scrubbing. Any value above one indicates the max "
"number of images that may be scrubbed in parallel."

#: glance/store/__init__.py:53
msgid "Turn on/off delayed delete."
msgstr "Turn on/off delayed delete."

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr "Role used to identify an authenticated user as administrator."

#: glance/scrubber.py:51 glance/registry/client/v1/api.py:34
msgid ""
"Whether to pass through headers containing user and tenant information when "
"making requests to the registry. This allows the registry to use the context "
"middleware without keystonemiddleware's auth_token middleware, removing "
"calls to the keystone auth service. It is recommended that when using this "
"option, secure communication between glance api and glance registry is "
"ensured by means other than auth_token middleware."
msgstr ""
"Whether to pass through headers containing user and tenant information when "
"making requests to the registry. This allows the registry to use the context "
"middleware without keystonemiddleware's auth_token middleware, removing "
"calls to the keystone auth service. It is recommended that when using this "
"option, secure communication between glance api and glance registry is "
"ensured by means other than auth_token middleware."

#: glance/scrubber.py:64
msgid "Loop time between checking for new items to schedule for delete."
msgstr "Loop time between checking for new items to schedule for delete."

#: glance/scrubber.py:72
msgid ""
"Run as a long-running process. When not specified (the default) run the "
"scrub operation once and then exits. When specified do not exit and run "
"scrub on wakeup_time interval as specified in the config."
msgstr ""
"Run as a long-running process. When not specified (the default), runs the "
"scrub operation once and then exits. When specified, does not exit and runs "
"scrub on wakeup_time interval as specified in the config."

#: glance/api/authorization.py:197 glance/api/authorization.py:380
msgid "Public images do not have members."
msgstr "Public images do not have members."

#: glance/api/authorization.py:118 glance/api/authorization.py:129
#, python-format
msgid "You cannot get image member for %s"
msgstr "You cannot get image member for %s"

#: glance/api/authorization.py:137
#, python-format
msgid "You cannot delete image member for %s"
msgstr "You cannot delete image member for %s"

#: glance/api/authorization.py:146
#, python-format
msgid "You cannot add image member for %s"
msgstr "You cannot add image member for %s"

#: glance/api/authorization.py:155
#, python-format
msgid "You cannot update image member %s"
msgstr "You cannot update image member %s"

#: glance/api/authorization.py:174
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "You are not permitted to create images owned by '%s'."

#: glance/api/authorization.py:192
msgid "You are not permitted to create image members for the image."
msgstr "You are not permitted to create image members for the image."

#: glance/api/authorization.py:213
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr "You are not permitted to modify '%(attr)s' on this %(resource)s."

#: glance/api/authorization.py:223
msgid "You are not permitted to modify locations for this image."
msgstr "You are not permitted to modify locations for this image."

#: glance/api/authorization.py:247
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "You are not permitted to modify '%s' on this image."

#: glance/api/authorization.py:251
msgid "You are not permitted to modify this image."
msgstr "You are not permitted to modify this image."

#: glance/api/authorization.py:264
msgid "You are not permitted to modify tags on this image."
msgstr "You are not permitted to modify tags on this image."

#: glance/api/authorization.py:305
msgid "You are not permitted to delete this image."
msgstr "You are not permitted to delete this image."

#: glance/api/authorization.py:316
msgid "You are not permitted to upload data for this image."
msgstr "You are not permitted to upload data for this image."

#: glance/api/authorization.py:342
msgid "You are not permitted to deactivate this image."
msgstr "You are not permitted to deactivate this image."

#: glance/api/authorization.py:346
msgid "You are not permitted to reactivate this image."
msgstr "You are not permitted to reactivate this image."

#: glance/api/authorization.py:350 glance/api/authorization.py:354
#: glance/api/authorization.py:358
msgid "You are not permitted to set status on this task."
msgstr "You are not permitted to set status on this task."

#: glance/api/authorization.py:420
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr "You are not permitted to create this task with owner as: %s"

#: glance/api/authorization.py:515
msgid "You are not permitted to delete this namespace."
msgstr "You are not permitted to delete this namespace."

#: glance/api/authorization.py:519
msgid "You are not permitted to update this namespace."
msgstr "You are not permitted to update this namespace."

#: glance/api/authorization.py:545
#, python-format
msgid "You are not permitted to create namespace owned by '%s'"
msgstr "You are not permitted to create namespace owned by '%s'"

#: glance/api/authorization.py:604
msgid "You are not permitted to delete this object."
msgstr "You are not permitted to delete this object."

#: glance/api/authorization.py:608
msgid "You are not permitted to update this object."
msgstr "You are not permitted to update this object."

#: glance/api/authorization.py:633
#, python-format
msgid "You are not permitted to create object owned by '%s'"
msgstr "You are not permitted to create object owned by '%s'"

#: glance/api/authorization.py:696
msgid "You are not permitted to delete this meta_resource_type."
msgstr "You are not permitted to delete this meta_resource_type."

#: glance/api/authorization.py:722
#, python-format
msgid "You are not permitted to create resource_type owned by '%s'"
msgstr "You are not permitted to create resource_type owned by '%s'"

#: glance/api/authorization.py:780
msgid "You are not permitted to delete this property."
msgstr "You are not permitted to delete this property."

#: glance/api/authorization.py:784
msgid "You are not permitted to update this property."
msgstr "You are not permitted to update this property."

#: glance/api/authorization.py:809
#, python-format
msgid "You are not permitted to create property owned by '%s'"
msgstr "You are not permitted to create property owned by '%s'"

#: glance/api/authorization.py:867
msgid "You are not permitted to delete this tag."
msgstr "You are not permitted to delete this tag."

#: glance/api/authorization.py:871
msgid "You are not permitted to update this tag."
msgstr "You are not permitted to update this tag."

#: glance/api/authorization.py:892
msgid "Owner must be specified to create a tag."
msgstr "Owner must be specified to create a tag."

#: glance/api/authorization.py:895
#, python-format
msgid "You are not permitted to create a tag in the namespace owned by '%s'"
msgstr "You are not permitted to create a tag in the namespace owned by '%s'"

#: glance/api/common.py:56
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "Corrupt image download for image %(image_id)s"

#: glance/api/policy.py:220 glance/quota/__init__.py:343
#: glance/store/__init__.py:662
#, python-format
msgid "Invalid locations: %s"
msgstr "Invalid locations: %s"

#: glance/api/versions.py:27 glance/api/glare/versions.py:28
msgid ""
"Public url to use for versions endpoint. The default is None, which will use "
"the request's host_url attribute to populate the URL base. If Glance is "
"operating behind a proxy, you will want to change this to represent the "
"proxy's URL."
msgstr ""
"Public URL to use for versions endpoint. The default is None, which will use "
"the request's host_url attribute to populate the URL base. If Glance is "
"operating behind a proxy, you will want to change this to represent the "
"proxy's URL."

#: glance/api/glare/v0_1/glare.py:121
#, python-format
msgid "The format of the version %s is not valid. Use semver notation"
msgstr "The format of the version %s is not valid. Use semver notation"

#: glance/api/glare/v0_1/glare.py:188
#, python-format
msgid "Invalid Content-Type for work with %s"
msgstr "Invalid Content-Type for work with %s"

#: glance/api/glare/v0_1/glare.py:225
msgid "Invalid request PATCH for work with blob"
msgstr "Invalid request PATCH for work with blob"

#: glance/api/glare/v0_1/glare.py:239
#, python-format
msgid "Denying attempt to upload artifact because it exceeds the quota: %s"
msgstr "Denying attempt to upload artifact because it exceeds the quota: %s"

#: glance/api/glare/v0_1/glare.py:263
#, python-format
msgid "Failed to find artifact %(artifact_id)s to delete"
msgstr "Failed to find artifact %(artifact_id)s to delete"

#: glance/api/glare/v0_1/glare.py:267
#, python-format
msgid "Artifact %s could not be deleted because it is in use: %s"
msgstr "Artifact %s could not be deleted because it is in use: %s"

#: glance/api/glare/v0_1/glare.py:296
msgid "Unable to PUT to non-empty collection"
msgstr "Unable to PUT to non-empty collection"

#: glance/api/glare/v0_1/glare.py:299
msgid "Index is out of range"
msgstr "Index is out of range"

#: glance/api/glare/v0_1/glare.py:322
#, python-format
msgid "Not a blob property '%s'"
msgstr "Not a blob property '%s'"

#: glance/api/glare/v0_1/glare.py:330
#, python-format
msgid "Not a list property '%s'"
msgstr "Not a list property '%s'"

#: glance/api/glare/v0_1/glare.py:344
msgid "Error in store configuration. Adding artifacts to store is disabled."
msgstr "Error in store configuration. Adding artifacts to store is disabled."

#: glance/api/glare/v0_1/glare.py:366
#, python-format
msgid "Artifact storage media is full: %s"
msgstr "Artifact storage media is full: %s"

#: glance/api/glare/v0_1/glare.py:374
#, python-format
msgid "Artifact exceeds the storage quota: %s"
msgstr "Artifact exceeds the storage quota: %s"

#: glance/api/glare/v0_1/glare.py:382
#, python-format
msgid "The incoming artifact blob is too large: %s"
msgstr "The incoming artifact blob is too large: %s"

#: glance/api/glare/v0_1/glare.py:390
#, python-format
msgid "Insufficient permissions on artifact storage media: %s"
msgstr "Insufficient permissions on artifact storage media: %s"

#: glance/api/glare/v0_1/glare.py:423
msgid "Index is required"
msgstr "Index is required"

#: glance/api/glare/v0_1/glare.py:431
msgid "Not a list property"
msgstr "Not a list property"

#: glance/api/glare/v0_1/glare.py:435
msgid "Not a downloadable entity"
msgstr "Not a downloadable entity"

#: glance/api/v2/image_members.py:189 glance/api/v2/images.py:287
msgid "Body expected in request."
msgstr "Body expected in request."

#: glance/api/glare/v0_1/glare.py:577
#, python-format
msgid "Invalid headers \"Content-Type\": %s"
msgstr "Invalid headers \"Content-Type\": %s"

#: glance/api/glare/v0_1/glare.py:615
#, python-format
msgid "Invalid json body: %s"
msgstr "Invalid json body: %s"

#: glance/api/glare/v0_1/glare.py:628
msgid "Only list indexes are allowed for blob lists"
msgstr "Only list indexes are allowed for blob lists"

#: glance/api/glare/v0_1/glare.py:649
msgid "Limit param must be an integer"
msgstr "Limit param must be an integer"

#: glance/api/glare/v0_1/glare.py:653
msgid "Limit param must be positive"
msgstr "Limit param must be positive"

#: glance/api/glare/v0_1/glare.py:657
#, python-format
msgid "Limit param must not be higher than %d"
msgstr "Limit param must not be higher than %d"

#: glance/api/glare/v0_1/glare.py:667
#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. If type version is not set it must be one of "
"the following: %(available)s."
msgstr ""
"Invalid sort key: %(sort_key)s. If type version is not set it must be one of "
"the following: %(available)s."

#: glance/api/glare/v0_1/glare.py:678
#, python-format
msgid "Invalid sort key: %(sort_key)s. You cannot sort by this property"
msgstr "Invalid sort key: %(sort_key)s. You cannot sort by this property"

#: glance/api/v2/images.py:498 glance/api/v2/tasks.py:134
#, python-format
msgid "Invalid sort direction: %s"
msgstr "Invalid sort direction: %s"

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing "
"the request."
msgstr ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the image will be the authenticated user issuing the "
"request."

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."

#: glance/api/middleware/context.py:41
msgid "Limits request ID length."
msgstr "Limits request ID length."

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr "Unable to retrieve request id from context"

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr "Invalid service catalogue json."

#: glance/api/middleware/context.py:125
#, python-format
msgid "x-openstack-request-id is too long, max size %s"
msgstr "x-openstack-request-id is too long, max size %s"

#: glance/api/v1/controller.py:41 glance/api/v1/members.py:76
#, python-format
msgid "Image with identifier %s not found"
msgstr "Image with identifier %s not found"

#: glance/api/v1/controller.py:46
msgid "Forbidden image access"
msgstr "Forbidden image access"

#: glance/api/v1/controller.py:61
#, python-format
msgid "Image %s is deactivated"
msgstr "Image %s is deactivated"

#: glance/api/v1/controller.py:59
#, python-format
msgid "Image %s is not active"
msgstr "Image %s is not active"

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr "Store for image_id not found: %s"

#: glance/api/v1/controller.py:93
#, python-format
msgid "Data for image_id not found: %s"
msgstr "Data for image_id not found: %s"

#: glance/api/v1/images.py:87
#, python-format
msgid "Invalid time format for %s."
msgstr "Invalid time format for %s."

#: glance/api/v1/images.py:73
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr "Invalid disk format '%s' for image."

#: glance/api/v1/images.py:78
#, python-format
msgid "Invalid container format '%s' for image."
msgstr "Invalid container format '%s' for image."

#: glance/api/v1/images.py:94
msgid ""
"Invalid mix of disk and container formats. When setting a disk or container "
"format to one of 'aki', 'ari', or 'ami', the container and disk formats must "
"match."
msgstr ""
"Invalid mix of disk and container formats. When setting a disk or container "
"format to one of 'aki', 'ari', or 'ami', the container and disk formats must "
"match."

#: glance/api/v1/images.py:83
#, python-format
msgid "Image name too long: %d"
msgstr "Image name too long: %d"

#: glance/api/v1/images.py:139
#, python-format
msgid "Invalid checksum '%s': can't exceed 32 characters"
msgstr "Invalid checksum '%s': can't exceed 32 characters"

#: glance/api/v1/images.py:172
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"

#: glance/api/v1/images.py:194 glance/api/v1/images.py:238
#: glance/api/v1/images.py:272
#, python-format
msgid "Property '%s' is protected"
msgstr "Property '%s' is protected"

#: glance/api/v1/images.py:388
msgid "This operation is currently not permitted on Glance images details."
msgstr "This operation is currently not permitted on Glance images details."

#: glance/api/v1/images.py:380
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr "Bad value passed to filter %(filter)s got %(val)s"

#: glance/api/v1/images.py:477
#, python-format
msgid "External sources are not supported: '%s'"
msgstr "External sources are not supported: '%s'"

#: glance/api/v1/images.py:479
msgid "External source should not be empty"
msgstr "External source should not be empty"

#: glance/api/v1/images.py:493
#, python-format
msgid "Required store %s is invalid"
msgstr "Required store %s is invalid"

#: glance/api/v1/images.py:505 glance/api/v1/images.py:877
#, python-format
msgid "Invalid location %s"
msgstr "Invalid location %s"

#: glance/api/v1/images.py:528
#, python-format
msgid "An image with identifier %s already exists"
msgstr "An image with identifier %s already exists"

#: glance/api/v1/images.py:621
#, python-format
msgid "Failed to reserve image. Got error: %s"
msgstr "Failed to reserve image. Got error: %s"

#: glance/api/v1/images.py:542
msgid "Forbidden to reserve image."
msgstr "Forbidden to reserve image."

#: glance/api/v1/images.py:578
msgid "Content-Type must be application/octet-stream"
msgstr "Content-Type must be application/octet-stream"

#: glance/api/v1/images.py:729
#, python-format
msgid "Failed to activate image. Got error: %s"
msgstr "Failed to activate image. Got error: %s"

#: glance/api/v1/images.py:683
msgid "It's invalid to provide multiple image sources."
msgstr "It's invalid to provide multiple image sources."

#: glance/api/v1/images.py:709
#, python-format
msgid ""
"Provided image size must match the stored image size. (provided size: "
"%(ps)d, stored size: %(ss)d)"
msgstr ""
"Provided image size must match the stored image size. (provided size: "
"%(ps)d, stored size: %(ss)d)"

#: glance/api/v1/images.py:855
msgid "Disk format is not specified."
msgstr "Disk format is not specified."

#: glance/api/v1/images.py:860
msgid "Container format is not specified."
msgstr "Container format is not specified."

#: glance/api/v1/images.py:831
msgid "Forbidden to update deleted image."
msgstr "Forbidden to update deleted image."

#: glance/api/v1/images.py:978
#, python-format
msgid "Forbidden to modify '%(key)s' of %(status)s image."
msgstr "Forbidden to modify '%(key)s' of %(status)s image."

#: glance/api/v1/images.py:987
#, python-format
msgid "Forbidden to modify '%s' of image."
msgstr "Forbidden to modify '%s' of image."

#: glance/api/v1/images.py:860
msgid "Cannot upload to an unqueued image"
msgstr "Cannot upload to an unqueued image"

#: glance/store/__init__.py:469
#, python-format
msgid "Invalid location: %s"
msgstr "Invalid location: %s"

#: glance/api/v1/images.py:884
msgid "Attempted to update Location field for an image not in queued status."
msgstr ""
"Attempted to update Location field for an image not in queued status."

#: glance/api/v1/images.py:1069 glance/registry/api/v1/images.py:502
#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr "Failed to update image metadata. Got error: %s"

#: glance/api/v1/images.py:1076
#, python-format
msgid "Failed to find image to update: %s"
msgstr "Failed to find image to update: %s"

#: glance/api/v1/images.py:1083
#, python-format
msgid "Forbidden to update image: %s"
msgstr "Forbidden to update image: %s"

#: glance/api/v1/images.py:1091
msgid "Image operation conflicts"
msgstr "Image operation conflicts"

#: glance/api/v1/images.py:977
msgid "Image is protected"
msgstr "Image is protected"

#: glance/api/v1/images.py:984
#, python-format
msgid "Forbidden to delete a %s image."
msgstr "Forbidden to delete a %s image."

#: glance/api/v1/images.py:989
#, python-format
msgid "Image %s not found."
msgstr "Image %s not found."

#: glance/api/v1/images.py:1171
#, python-format
msgid "Failed to find image to delete: %s"
msgstr "Failed to find image to delete: %s"

#: glance/api/v1/images.py:1178
#, python-format
msgid "Forbidden to delete image: %s"
msgstr "Forbidden to delete image: %s"

#: glance/api/v1/images.py:1185 glance/api/v2/images.py:246
#, python-format
msgid "Image %(id)s could not be deleted because it is in use: %(exc)s"
msgstr "Image %(id)s could not be deleted because it is in use: %(exc)s"

#: glance/api/v1/images.py:1052 glance/store/__init__.py:231
#, python-format
msgid "Store for scheme %s not found"
msgstr "Store for scheme %s not found"

#: glance/api/v1/images.py:1091 glance/api/v1/upload_utils.py:202
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "Denying attempt to upload image larger than %d bytes."

#: glance/api/v1/members.py:41 glance/registry/api/v1/members.py:32
msgid "No authenticated user"
msgstr "No authenticated user"

#: glance/api/v1/members.py:53
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr "Image with identifier %s has been deleted."

#: glance/api/v1/members.py:80
msgid "Unauthorized image access"
msgstr "Unauthorised image access"

#: glance/api/v1/members.py:117 glance/common/exception.py:287
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for this "
"image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"The limit has been exceeded on the number of allowed image members for this "
"image. Attempted: %(attempted)s, Maximum: %(maximum)s"

#: glance/api/v1/upload_utils.py:115
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded image "
"(%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded image "
"(%(actual)s) did not match. Setting image status to 'killed'."

#: glance/api/v1/upload_utils.py:148
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload."
msgstr ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload."

#: glance/api/v1/upload_utils.py:195 glance/api/v2/image_data.py:175
msgid "Error in store configuration. Adding images to store is disabled."
msgstr "Error in store configuration. Adding images to store is disabled."

#: glance/api/v1/upload_utils.py:164
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr "Attempt to upload duplicate image: %s"

#: glance/api/v1/upload_utils.py:175
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr "Forbidden upload attempt: %s"

#: glance/api/v1/upload_utils.py:256 glance/api/v2/images.py:159
#, python-format
msgid "Denying attempt to upload image because it exceeds the quota: %s"
msgstr "Denying attempt to upload image because it exceeds the quota: %s"

#: glance/api/v1/upload_utils.py:233
msgid "Client disconnected before sending all data to backend"
msgstr "Client disconnected before sending all data to backend"

#: glance/api/v1/upload_utils.py:241
#, python-format
msgid "Failed to upload image %s"
msgstr "Failed to upload image %s"

#: glance/api/v2/image_data.py:139
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload, cleaning up the chunks uploaded."
msgstr ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload, cleaning up the chunks uploaded."

#: glance/api/v2/image_data.py:154
#, python-format
msgid ""
"Authentication error - the token may have expired during file upload. "
"Deleting image data for %s."
msgstr ""
"Authentication error - the token may have expired during file upload. "
"Deleting image data for %s."

#: glance/api/v2/image_data.py:114
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr "Image exceeds the storage quota: %s"

#: glance/api/v2/image_data.py:121
#, python-format
msgid "The incoming image is too large: %s"
msgstr "The incoming image is too large: %s"

#: glance/api/v2/image_data.py:256
msgid ""
"The requested image has been deactivated. Image data download is forbidden."
msgstr ""
"The requested image has been deactivated. Image data download is forbidden."

#: glance/api/v2/image_members.py:56
#, python-format
msgid "Error fetching members of image %(image_id)s: %(inner_msg)s"
msgstr "Error fetching members of image %(image_id)s: %(inner_msg)s"

#: glance/api/v2/image_members.py:71
#, python-format
msgid "You are not authorized to lookup image %s."
msgstr "You are not authorised to lookup image %s."

#: glance/api/v2/image_members.py:80
#, python-format
msgid "%(m_id)s not found in the member list of the image %(i_id)s."
msgstr "%(m_id)s not found in the member list of the image %(i_id)s."

#: glance/api/v2/image_members.py:86
#, python-format
msgid "You are not authorized to lookup the members of the image %s."
msgstr "You are not authorised to lookup the members of the image %s."

#: glance/api/v2/image_members.py:119
#, python-format
msgid "Not allowed to create members for image %s."
msgstr "Not allowed to create members for image %s."

#: glance/api/v2/image_members.py:123
#, python-format
msgid "Member %(member_id)s is duplicated for image %(image_id)s"
msgstr "Member %(member_id)s is duplicated for image %(image_id)s"

#: glance/api/v2/image_members.py:129
#, python-format
msgid "Image member limit exceeded for image %(id)s: %(e)s:"
msgstr "Image member limit exceeded for image %(id)s: %(e)s:"

#: glance/api/v2/image_members.py:161
#, python-format
msgid "Not allowed to update members for image %s."
msgstr "Not allowed to update members for image %s."

#: glance/api/v2/image_members.py:165
#, python-format
msgid "Incorrect request: %s"
msgstr "Incorrect request: %s"

#: glance/api/v2/image_members.py:197
#, python-format
msgid "Not allowed to list members for image %s."
msgstr "Not allowed to list members for image %s."

#: glance/api/v2/image_members.py:239
#, python-format
msgid "Not allowed to delete members for image %s."
msgstr "Not allowed to delete members for image %s."

#: glance/api/v2/image_members.py:200
msgid "Member to be added not specified"
msgstr "Did not specify the member to be added"

#: glance/api/v2/image_members.py:203
msgid "Member can't be empty"
msgstr "Member can't be empty"

#: glance/api/v2/image_members.py:269
msgid "Expected a member in the form: {\"member\": \"image_id\"}"
msgstr "Expected a member in the form: {\"member\": \"image_id\"}"

#: glance/api/v2/image_members.py:212
msgid "Status not specified"
msgstr "Status not specified"

#: glance/api/v2/image_members.py:282
msgid "Expected a status in the form: {\"status\": \"status\"}"
msgstr "Expected a status in the form: {\"status\": \"status\"}"

#: glance/api/v2/image_members.py:267
msgid "An identifier for the image member (tenantId)"
msgstr "An identifier for the image member (tenantId)"

#: glance/api/v2/image_members.py:271 glance/api/v2/images.py:644
msgid "An identifier for the image"
msgstr "An identifier for the image"

#: glance/api/v2/image_members.py:277
msgid "Date and time of image member creation"
msgstr "Date and time of image member creation"

#: glance/api/v2/image_members.py:284
msgid "Date and time of last modification of image member"
msgstr "Date and time of last modification of image member"

#: glance/api/v2/image_members.py:289
msgid "The status of this image member"
msgstr "The status of this image member"

#: glance/api/v2/image_tags.py:56
#, python-format
msgid "Not allowed to update tags for image %s."
msgstr "Not allowed to update tags for image %s."

#: glance/api/v2/image_tags.py:60
#, python-format
msgid "Could not update image: %s"
msgstr "Could not update image: %s"

#: glance/api/v2/image_tags.py:65
#, python-format
msgid "Image tag limit exceeded for image %(id)s: %(e)s:"
msgstr "Image tag limit exceeded for image %(id)s: %(e)s:"

#: glance/api/v2/image_tags.py:85
#, python-format
msgid "Not allowed to delete tags for image %s."
msgstr "Not allowed to delete tags for image %s."

#: glance/api/v2/images.py:178
msgid "Cannot set locations to empty list."
msgstr "Cannot set locations to empty list."

#: glance/api/v2/images.py:183
msgid "Owner can't be updated by non admin."
msgstr "Owner can't be updated by non admin."

#: glance/api/v2/images.py:156 glance/api/v2/images.py:184
#, python-format
msgid "Property %s does not exist."
msgstr "Property %s does not exist."

#: glance/api/v2/images.py:168
#, python-format
msgid "Property %s already present."
msgstr "Property %s already present."

#: glance/api/v2/images.py:179
#, python-format
msgid "Property %s may not be removed."
msgstr "Property %s may not be removed."

#: glance/api/v2/images.py:197
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr "Failed to find image %(image_id)s to delete"

#: glance/api/v2/images.py:273
msgid "It's not allowed to update locations if locations are invisible."
msgstr "It's not allowed to update locations if locations are invisible."

#: glance/api/v2/images.py:291
msgid "It's not allowed to add locations if locations are invisible."
msgstr "It's not allowed to add locations if locations are invisible."

#: glance/api/v2/images.py:239
msgid "Invalid position for adding a location."
msgstr "Invalid position for adding a location."

#: glance/api/v2/images.py:312
msgid "It's not allowed to remove locations if locations are invisible."
msgstr "It's not allowed to remove locations if locations are invisible."

#: glance/api/v2/images.py:319
msgid "Cannot remove last location in the image."
msgstr "Cannot remove last location in the image."

#: glance/api/v2/images.py:254
msgid "Invalid position for removing a location."
msgstr "Invalid position for removing a location."

#: glance/api/v2/images.py:295 glance/api/v2/images.py:394
#, python-format
msgid "Attribute '%s' is read-only."
msgstr "Attribute '%s' is read-only."

#: glance/api/v2/images.py:405
#, python-format
msgid ""
"Unable to find `op` in JSON Schema change. It must be one of the following: "
"%(available)s."
msgstr ""
"Unable to find `op` in JSON Schema change. It must be one of the following: "
"%(available)s."

#: glance/api/v2/images.py:410
#, python-format
msgid ""
"Invalid operation: `%(op)s`. It must be one of the following: %(available)s."
msgstr ""
"Invalid operation: `%(op)s`. It must be one of the following: %(available)s."

#: glance/api/v2/images.py:327
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\", or "
"\"replace\"."
msgstr ""
"Operation objects must contain only one member named \"add\", \"remove\", or "
"\"replace\"."

#: glance/api/v2/images.py:332
msgid ""
"Operation objects must contain exactly one member named \"add\", \"remove\", "
"or \"replace\"."
msgstr ""
"Operation objects must contain exactly one member named \"add\", \"remove\", "
"or \"replace\"."

#: glance/api/v2/images.py:319 glance/api/v2/images.py:341
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "Unable to find '%s' in JSON Schema change"

#: glance/api/v2/images.py:369
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "Pointer `%s` does not start with \"/\"."

#: glance/api/v2/images.py:372
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr "Pointer `%s` contains adjacent \"/\"."

#: glance/api/v2/images.py:375
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr "Pointer `%s` end with \"/\"."

#: glance/api/v2/images.py:378
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr "Pointer `%s` does not contains valid token."

#: glance/api/v2/images.py:381
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""
"Pointer `%s` contains \"~\" not part of a recognised escape sequence."

#: glance/api/v2/images.py:387
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "Operation \"%s\" requires a member named \"value\"."

#: glance/api/v2/images.py:397
#, python-format
msgid "Attribute '%s' is reserved."
msgstr "Attribute '%s' is reserved."

#: glance/api/v2/images.py:427
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr "Invalid JSON pointer for this resource: '/%s'"

#: glance/api/v2/images.py:439
msgid "Unrecognized JSON Schema draft version"
msgstr "Unrecognised JSON Schema draft version"

#: glance/api/v2/images.py:460
msgid "Request body must be a JSON array of operation objects."
msgstr "Request body must be a JSON array of operation objects."

#: glance/api/v2/images.py:465
msgid "Operations must be JSON objects."
msgstr "Operations must be JSON objects."

#: glance/api/v2/images.py:487 glance/api/v2/tasks.py:164
#: glance/registry/api/v1/images.py:246
msgid "limit param must be an integer"
msgstr "limit param must be an integer"

#: glance/api/v2/images.py:491 glance/api/v2/tasks.py:168
#: glance/registry/api/v1/images.py:249
msgid "limit param must be positive"
msgstr "limit param must be positive"

#: glance/api/v2/images.py:596
#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. It must be one of the following: "
"%(available)s."
msgstr ""
"Invalid sort key: %(sort_key)s. It must be one of the following: "
"%(available)s."

#: glance/api/v2/images.py:505
#, python-format
msgid "Invalid status: %s"
msgstr "Invalid status: %s"

#: glance/api/v2/images.py:514
#, python-format
msgid "Invalid visibility value: %s"
msgstr "Invalid visibility value: %s"

#: glance/api/v2/images.py:626
msgid "The \"changes-since\" filter is no longer available on v2."
msgstr "The \"changes-since\" filter is no longer available on v2."

#: glance/api/v2/images.py:645
msgid "Old and new sorting syntax cannot be combined"
msgstr "Old and new sorting syntax cannot be combined"

#: glance/api/v2/images.py:676
msgid "Number of sort dirs does not match the number of sort keys"
msgstr "Number of sort dirs does not match the number of sort keys"

#: glance/api/v2/images.py:650
msgid "Descriptive name for the image"
msgstr "Descriptive name for the image"

#: glance/api/v2/images.py:848
msgid "Status of the image"
msgstr "Status of the image"

#: glance/api/v2/images.py:661
msgid "Scope of image accessibility"
msgstr "Scope of image accessibility"

#: glance/api/v2/images.py:666
msgid "If true, image will not be deletable."
msgstr "If true, image will not be deletable."

#: glance/api/v2/images.py:864
msgid "md5 hash of image contents."
msgstr "MD5 hash of image contents."

#: glance/api/v2/images.py:675
msgid "Owner of the image"
msgstr "Owner of the image"

#: glance/api/v2/images.py:875
msgid "Size of image file in bytes"
msgstr "Size of image file in bytes"

#: glance/api/v2/images.py:880
msgid "Virtual size of image in bytes"
msgstr "Virtual size of image in bytes"

#: glance/api/v2/images.py:688
msgid "Format of the container"
msgstr "Format of the container"

#: glance/api/v2/images.py:693
msgid "Format of the disk"
msgstr "Format of the disk"

#: glance/api/v2/images.py:895
msgid "Date and time of image registration"
msgstr "Date and time of image registration"

#: glance/api/v2/images.py:904
msgid "Date and time of the last image modification"
msgstr "Date and time of the last image modification"

#: glance/api/v2/images.py:712
msgid "List of strings related to the image"
msgstr "List of strings related to the image"

#: glance/api/v2/images.py:919
msgid "URL to access the image file kept in external store"
msgstr "URL to access the image file kept in external store"

#: glance/api/v2/images.py:725
msgid "Amount of ram (in MB) required to boot image."
msgstr "Amount of ram (in MB) required to boot image."

#: glance/api/v2/images.py:729
msgid "Amount of disk space (in GB) required to boot image."
msgstr "Amount of disk space (in GB) required to boot image."

#: glance/api/v2/images.py:934
msgid "An image self url"
msgstr "An image self URL"

#: glance/api/v2/images.py:939
msgid "An image file url"
msgstr "An image file URL"

#: glance/api/v2/images.py:944
msgid "An image schema url"
msgstr "An image schema URL"

#: glance/api/v2/images.py:759
msgid "A set of URLs to access the image file kept in external store"
msgstr "A set of URLs to access the image file kept in external store"

#: glance/api/v2/metadef_namespaces.py:675
msgid "The unique namespace text."
msgstr "The unique namespace text."

#: glance/api/v2/metadef_namespaces.py:680
msgid "The user friendly name for the namespace. Used by UI if available."
msgstr "The user friendly name for the namespace. Used by UI if available."

#: glance/api/v2/metadef_namespaces.py:686
msgid "Provides a user friendly description of the namespace."
msgstr "Provides a user friendly description of the namespace."

#: glance/api/v2/metadef_namespaces.py:692
msgid "Scope of namespace accessibility."
msgstr "Scope of namespace accessibility."

#: glance/api/v2/metadef_namespaces.py:697
msgid "If true, namespace will not be deletable."
msgstr "If true, namespace will not be deletable."

#: glance/api/v2/metadef_namespaces.py:701
msgid "Owner of the namespace."
msgstr "Owner of the namespace."

#: glance/api/v2/metadef_namespaces.py:707
msgid "Date and time of namespace creation"
msgstr "Date and time of namespace creation"

#: glance/api/v2/metadef_namespaces.py:713
msgid "Date and time of the last namespace modification"
msgstr "Date and time of the last namespace modification"

#: glance/api/v2/metadef_objects.py:197
msgid "Date and time of object creation"
msgstr "Date and time of object creation"

#: glance/api/v2/metadef_objects.py:203
msgid "Date and time of the last object modification"
msgstr "Date and time of the last object modification"

#: glance/api/v2/metadef_properties.py:94
#, python-format
msgid ""
"Property %(property_name)s does not start with the expected resource type "
"association prefix of '%(prefix)s'."
msgstr ""
"Property %(property_name)s does not start with the expected resource type "
"association prefix of '%(prefix)s'."

#: glance/api/v2/metadef_resource_types.py:131
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:125
#, python-format
msgid "Failed to find resource type %(resourcetype)s to delete"
msgstr "Failed to find resource type %(resourcetype)s to delete"

#: glance/api/v2/metadef_resource_types.py:204
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:199
msgid ""
"Resource type names should be aligned with Heat resource types whenever "
"possible: "
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"
msgstr ""
"Resource type names should be aligned with Heat resource types whenever "
"possible: "
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"

#: glance/api/v2/metadef_resource_types.py:212
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:207
msgid ""
"Specifies the prefix to use for the given resource type. Any properties in "
"the namespace should be prefixed with this prefix when being applied to the "
"specified resource type. Must include prefix separator (e.g. a colon :)."
msgstr ""
"Specifies the prefix to use for the given resource type. Any properties in "
"the namespace should be prefixed with this prefix when being applied to the "
"specified resource type. Must include prefix separator (e.g. a colon :)."

#: glance/api/v2/metadef_resource_types.py:221
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:216
msgid ""
"Some resource types allow more than one key / value pair per instance.  For "
"example, Cinder allows user and image metadata on volumes. Only the image "
"properties metadata is evaluated by Nova (scheduling or drivers). This "
"property allows a namespace target to remove the ambiguity."
msgstr ""
"Some resource types allow more than one key / value pair per instance.  For "
"example, Cinder allows user and image metadata on volumes. Only the image "
"properties metadata is evaluated by Nova (scheduling or drivers). This "
"property allows a namespace target to remove the ambiguity."

#: glance/api/v2/metadef_resource_types.py:233
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:228
msgid "Date and time of resource type association"
msgstr "Date and time of resource type association"

#: glance/api/v2/metadef_resource_types.py:239
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:234
msgid "Date and time of the last resource type association modification"
msgstr "Date and time of the last resource type association modification"

#: glance/api/v2/metadef_tags.py:198
msgid "Date and time of tag creation"
msgstr "Date and time of tag creation"

#: glance/api/v2/metadef_tags.py:204
msgid "Date and time of the last tag modification"
msgstr "Date and time of the last tag modification"

#: glance/api/v2/tasks.py:137
msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."

#: glance/api/v2/tasks.py:143
#, python-format
msgid "Invalid status value: %s"
msgstr "Invalid status value: %s"

#: glance/api/v2/tasks.py:149
#, python-format
msgid "Invalid type value: %s"
msgstr "Invalid type value: %s"

#: glance/api/v2/tasks.py:156 glance/registry/api/v1/images.py:258
msgid "Invalid marker format"
msgstr "Invalid marker format"

#: glance/api/v2/tasks.py:177
#, python-format
msgid "Task '%s' is required"
msgstr "Task '%s' is required"

#: glance/api/v2/tasks.py:292
msgid "An identifier for the task"
msgstr "An identifier for the task"

#: glance/api/v2/tasks.py:293
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"
msgstr ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"

#: glance/api/v2/tasks.py:298
msgid "The type of task represented by this content"
msgstr "The type of task represented by this content"

#: glance/api/v2/tasks.py:305
msgid "The current status of this task"
msgstr "The current status of this task"

#: glance/api/v2/tasks.py:315
msgid "The parameters required by task, JSON blob"
msgstr "The parameters required by task, JSON blob"

#: glance/api/v2/tasks.py:319
msgid "The result of current task, JSON blob"
msgstr "The result of current task, JSON blob"

#: glance/api/v2/tasks.py:323
msgid "An identifier for the owner of this task"
msgstr "An identifier for the owner of this task"

#: glance/api/v2/tasks.py:327
msgid ""
"Human-readable informative message only included when appropriate (usually "
"on failure)"
msgstr ""
"Human-readable informative message only included when appropriate (usually "
"on failure)"

#: glance/api/v2/tasks.py:332
msgid "Datetime when this resource would be subject to removal"
msgstr "Datetime when this resource would be subject to removal"

#: glance/api/v2/tasks.py:337
msgid "Datetime when this resource was created"
msgstr "Datetime when this resource was created"

#: glance/api/v2/tasks.py:341
msgid "Datetime when this resource was updated"
msgstr "Datetime when this resource was updated"

#: glance/async/taskflow_executor.py:40
msgid "The mode in which the engine will run. Can be 'serial' or 'parallel'."
msgstr ""
"The mode in which the engine will run. Can be 'serial' or 'parallel'."

#: glance/async/taskflow_executor.py:44
msgid ""
"The number of parallel activities executed at the same time by the engine. "
"The value can be greater than one when the engine mode is 'parallel'."
msgstr ""
"The number of parallel activities executed at the same time by the engine. "
"The value can be greater than one when the engine mode is 'parallel'."

#: glance/async/taskflow_executor.py:144
msgid "Task failed due to Internal Error"
msgstr "Task failed due to Internal Error"

#: glance/async/flows/base_import.py:95
#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Missing work dir: "
"%(work_dir)s"
msgstr ""
"%(task_id)s of %(task_type)s not configured properly. Missing work dir: "
"%(work_dir)s"

#: glance/async/flows/base_import.py:127
#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Could not load the "
"filesystem store"
msgstr ""
"%(task_id)s of %(task_type)s not configured properly. Could not load the "
"filesystem store"

#: glance/async/flows/base_import.py:170
#, python-format
msgid "File %(path)s has invalid backing file %(bfile)s, aborting."
msgstr "File %(path)s has invalid backing file %(bfile)s, aborting."

#: glance/async/flows/convert.py:31
msgid ""
"The format to which images will be automatically converted. When using the "
"RBD backend, this should be set to 'raw'"
msgstr ""
"The format to which images will be automatically converted. When using the "
"RBD backend, this should be set to 'raw'"

#: glance/async/flows/ovf_process.py:112
msgid "OVA extract is limited to admin"
msgstr "OVA extract is limited to admin"

#: glance/async/flows/ovf_process.py:153
msgid "Could not find OVF file in OVA archive file."
msgstr "Could not find OVF file in OVA archive file."

#: glance/async/flows/ovf_process.py:205
msgid "Currently, OVA packages containing multiple disk are not supported."
msgstr "Currently, OVA packages containing multiple disk are not supported."

#: glance/async/flows/ovf_process.py:246
msgid ""
"OVF metadata of interest was not specified in ovf-metadata.json config file. "
"Please set \"cim_pasd\" to a list of interested "
"CIM_ProcessorAllocationSettingData properties."
msgstr ""
"OVF metadata of interest was not specified in ovf-metadata.json config file. "
"Please set \"cim_pasd\" to a list of interested "
"CIM_ProcessorAllocationSettingData properties."

#: glance/async/flows/ovf_process.py:252
msgid "OVF properties config file \"ovf-metadata.json\" was not found."
msgstr "OVF properties config file \"ovf-metadata.json\" was not found."

#: glance/cmd/__init__.py:41
#, python-format
msgid ""
"It appears that the eventlet module has been imported prior to setting "
"%s='yes'. It is currently necessary to disable eventlet.greendns if using "
"ipv6 since eventlet.greendns currently breaks with ipv6 addresses. Please "
"ensure that eventlet is not imported prior to this being set."
msgstr ""
"It appears that the eventlet module has been imported prior to setting "
"%s='yes'. It is currently necessary to disable eventlet.greendns if using "
"IPV6 since eventlet.greendns currently breaks with ipv6 addresses. Please "
"ensure that eventlet is not imported prior to this being set."

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr "%(serv)s appears to already be running: %(pid)s"

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr "Removing stale pid file %s"

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr "Unable to increase file descriptor limit.  Running as non-root?"

#: glance/cmd/control.py:164
#, python-format
msgid "%(verb)sing %(serv)s with %(conf)s"
msgstr "%(verb)sing %(serv)s with %(conf)s"

#: glance/cmd/control.py:161
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr "%(verb)sing %(serv)s"

#: glance/cmd/control.py:176
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr "unable to launch %(serv)s. Got error: %(e)s"

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr "%(serv)s (pid %(pid)s) is running..."

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr "%s is stopped"

#: glance/cmd/control.py:225
#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"

#: glance/cmd/control.py:246
#, python-format
msgid "Reload of %(serv)s not supported"
msgstr "Reload of %(serv)s not supported"

#: glance/cmd/control.py:254
#, python-format
msgid "Server %(serv)s is stopped"
msgstr "Server %(serv)s is stopped"

#: glance/cmd/control.py:259
#, python-format
msgid "Reloading %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "Reloading %(serv)s (pid %(pid)s) with signal(%(sig)s)"

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr "Process %d not running"

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr "%s is already stopped"

#: glance/cmd/control.py:372
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr "Suppressed re-spawn as %(serv)s was %(rsn)s."

#: glance/cmd/manage.py:163
#, python-format
msgid "Invalid int value for age_in_days: %(age_in_days)s"
msgstr "Invalid int value for age_in_days: %(age_in_days)s"

#: glance/cmd/manage.py:169
#, python-format
msgid "Invalid int value for max_rows: %(max_rows)s"
msgstr "Invalid int value for max_rows: %(max_rows)s"

#: glance/cmd/manage.py:173
msgid "Must supply a positive, non-zero value for age."
msgstr "Must supply a positive, non-zero value for age."

#: glance/cmd/manage.py:175
msgid "Maximal age is count of days since epoch."
msgstr "Maximal age is count of days since epoch."

#: glance/cmd/manage.py:177
msgid "Minimal rows limit is 1."
msgstr "Minimal rows limit is 1."

#: glance/cmd/manage.py:330
msgid "Available categories:"
msgstr "Available categories:"

#: glance/cmd/manage.py:332
#, python-format
msgid "\t%s"
msgstr "\t%s"

#: glance/cmd/replicator.py:55
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did not "
"find it. This indicates that we do not have permissions to see all the "
"images on the slave server."
msgstr ""
"The image %s is already present on the slave, but our check for it did not "
"find it. This indicates that we do not have permissions to see all the "
"images on the slave server."

#: glance/cmd/replicator.py:282 glance/cmd/replicator.py:319
#: glance/cmd/replicator.py:404 glance/cmd/replicator.py:483
#: glance/cmd/replicator.py:560
msgid "Too few arguments."
msgstr "Too few arguments."

#: glance/cmd/replicator.py:303
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr "Total size is %(size)d bytes across %(img_count)d images"

#: glance/cmd/replicator.py:717
#, python-format
msgid "Unknown command: %s"
msgstr "Unknown command: %s"

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr "Unexpected response: %s"

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "Unknown auth strategy '%s'"

#: glance/common/client.py:240
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert, "
"however you have failed to supply either a key_file parameter or set the "
"GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a cert, "
"however you have failed to supply either a key_file parameter or set the "
"GLANCE_CLIENT_KEY_FILE environ variable"

#: glance/common/client.py:248
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the "
"GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the "
"GLANCE_CLIENT_CERT_FILE environ variable"

#: glance/common/client.py:257
#, python-format
msgid "The key file you specified %s does not exist"
msgstr "The key file you specified %s does not exist"

#: glance/common/client.py:264
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "The cert file you specified %s does not exist"

#: glance/common/client.py:271
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "The CA file you specified %s does not exist"

#: glance/common/client.py:410
#, python-format
msgid "Constructed URL: %s"
msgstr "Constructed URL: %s"

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the service "
"name removed. For example, if your paste section name is [pipeline:glance-"
"api-keystone] use the value \"keystone\""
msgstr ""
"Partial name of a pipeline in your paste configuration file with the service "
"name removed. For example, if your paste section name is [pipeline:glance-"
"api-keystone], use the value \"keystone\""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr "Name of the paste configuration file."

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr "Supported values for the 'container_format' image attribute"

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr "Supported values for the 'disk_format' image attribute"

#: glance/common/config.py:60
msgid ""
"Time in hours for which a task lives after, either succeeding or failing"
msgstr ""
"Time in hours for which a task lives after, either succeeding or failing"

#: glance/common/config.py:67
msgid "Specifies which task executor to be used to run the task scripts."
msgstr "Specifies which task executor to be used to run the task scripts."

#: glance/common/config.py:70
msgid ""
"Work dir for asynchronous task operations. The directory set here will be "
"used to operate over images - normally before they are imported in the "
"destination store. When providing work dir, make sure enough space is "
"provided for concurrent tasks to run efficiently without running out of "
"space. A rough estimation can be done by multiplying the number of "
"`max_workers` - or the N of workers running - by an average image size (e.g "
"500MB). The image size estimation should be done based on the average size "
"in your deployment. Note that depending on the tasks running you may need to "
"multiply this number by some factor depending on what the task does. For "
"example, you may want to double the available size if image conversion is "
"enabled. All this being said, remember these are just estimations and you "
"should do them based on the worst case scenario and be prepared to act in "
"case they were wrong."
msgstr ""
"Work directory for asynchronous task operations. The directory set here will "
"be used to operate over images - normally before they are imported in the "
"destination store. When providing a work directory, make sure enough space "
"is provided for concurrent tasks to run efficiently without running out of "
"space. A rough estimation can be done by multiplying the number of "
"`max_workers` - or the N of workers running - by an average image size (e.g "
"500MB). The image size estimation should be done based on the average size "
"in your deployment. Note that depending on the tasks running you may need to "
"multiply this number by some factor depending on what the task does. For "
"example, you may want to double the available size if image conversion is "
"enabled. All this being said, remember these are just estimations and you "
"should do them based on the worst case scenario and be prepared to act in "
"case they were wrong."

#: glance/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"

#: glance/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."

#: glance/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values evaluate "
"to unlimited."
msgstr ""
"Maximum number of properties allowed on an image. Negative values evaluate "
"to unlimited."

#: glance/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."

#: glance/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""
"Maximum number of locations allowed on an image. Negative values evaluate to "
"unlimited."

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr "Python module path of data access API"

#: glance/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not specified "
"explicitly in the request"
msgstr ""
"Default value for the number of items returned by a request if not specified "
"explicitly in the request"

#: glance/common/config.py:87
msgid ""
"Maximum permissible number of items that could be returned by a request"
msgstr ""
"Maximum permissible number of items that could be returned by a request"

#: glance/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image properties. "
"Revealing storage location can be a security risk, so use this setting with "
"caution!"
msgstr ""
"Whether to include the backend image storage location in image properties. "
"Revealing storage location can be a security risk, so use this setting with "
"caution!"

#: glance/common/config.py:119
msgid ""
"Whether to include the backend image locations in image properties. For "
"example, if using the file system store a URL of \"file:///path/to/image\" "
"will be returned to the user in the 'direct_url' meta-data field. Revealing "
"storage location can be a security risk, so use this setting with caution! "
"Setting this to true overrides the show_image_direct_url option."
msgstr ""
"Whether to include the backend image locations in image properties. For "
"example, if using the file system store a URL of \"file:///path/to/image\" "
"will be returned to the user in the 'direct_url' meta-data field. Revealing "
"storage location can be a security risk, so use this setting with caution! "
"Setting this to true overrides the show_image_direct_url option."

#: glance/common/config.py:131
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to 1099511627776 "
"bytes (1 TB).WARNING: this value should only be increased after careful "
"consideration and must be set to a value under 8 EB (9223372036854775808)."
msgstr ""
"Maximum size of image a user can upload in bytes. Defaults to 1099511627776 "
"bytes (1 TB). WARNING: this value should only be increased after careful "
"consideration and must be set to a value under 8 EB (9223372036854775808)."

#: glance/common/config.py:137
msgid ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited.Optional unit can be specified for the value. Accepted units are "
"B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, GigaBytes and "
"TeraBytes respectively. If no unit is specified then Bytes is assumed. Note "
"that there should not be any space between value and unit and units are case "
"sensitive."
msgstr ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited. An optional unit can be specified for the value. Accepted units "
"are B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, GigaBytes "
"and TeraBytes respectively. If no unit is specified then Bytes is assumed. "
"Note that there should not be any space between value and unit and units are "
"case sensitive."

#: glance/common/config.py:107
msgid "Deploy the v1 OpenStack Images API."
msgstr "Deploy the v1 OpenStack Images API."

#: glance/common/config.py:109
msgid "Deploy the v2 OpenStack Images API."
msgstr "Deploy the v2 OpenStack Images API."

#: glance/common/config.py:111
msgid "Deploy the v1 OpenStack Registry API."
msgstr "Deploy the v1 OpenStack Registry API."

#: glance/common/config.py:113
msgid "Deploy the v2 OpenStack Registry API."
msgstr "Deploy the v2 OpenStack Registry API."

#: glance/common/config.py:115
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr "The hostname/IP of the pydev process listening for debug connections"

#: glance/common/config.py:118
msgid "The port on which a pydev process is listening for connections."
msgstr "The port on which a pydev process is listening for connections."

#: glance/common/config.py:161
msgid ""
"AES key for encrypting store 'location' metadata. This includes, if used, "
"Swift or S3 credentials. Should be set to a random string of length 16, 24 "
"or 32 bytes"
msgstr ""
"AES key for encrypting store 'location' metadata. This includes, if used, "
"Swift or S3 credentials. Should be set to a random string of length 16, 24 "
"or 32 bytes"

#: glance/common/config.py:166
msgid ""
"Digest algorithm which will be used for digital signature. Use the command "
"\"openssl list-message-digest-algorithms\" to get the available algorithms "
"supported by the version of OpenSSL on the platform. Examples are \"sha1\", "
"\"sha256\", \"sha512\", etc."
msgstr ""
"Digest algorithm which will be used for digital signature. Use the command "
"\"openssl list-message-digest-algorithms\" to get the available algorithms "
"supported by the version of OpenSSL on the platform. Examples are \"sha1\", "
"\"sha256\", \"sha512\", etc."

#: glance/common/config.py:179
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr "Unable to locate paste config file for %s."

#: glance/common/config.py:218
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr "An unknown exception occurred"

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "Missing required credential: %(required)s"

#: glance/common/exception.py:67
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr "An object with the specified identifier was not found."

#: glance/common/exception.py:80
msgid "The Store URI was malformed."
msgstr "The Store URI was malformed."

#: glance/common/exception.py:84
msgid "An object with the same identifier already exists."
msgstr "An object with the same identifier already exists."

#: glance/common/exception.py:88
msgid "An object with the same identifier is currently being operated on."
msgstr "An object with the same identifier is currently being operated on."

#: glance/common/exception.py:97
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."

#: glance/common/exception.py:106
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "Connect error/bad request to Auth service at URL %(url)s."

#: glance/common/exception.py:110
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "Auth service at URL %(url)s not found."

#: glance/common/exception.py:114
msgid "Authorization failed."
msgstr "Authorisation failed."

#: glance/common/exception.py:118
msgid "You are not authenticated."
msgstr "You are not authenticated."

#: glance/common/exception.py:112
#, python-format
msgid "Image upload problem: %s"
msgstr "Image upload problem: %s"

#: glance/common/exception.py:122 glance/common/exception.py:126
msgid "You are not authorized to complete this action."
msgstr "You are not authorised to complete this action."

#: glance/common/exception.py:130
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "Image %(image_id)s is protected and cannot be deleted."

#: glance/common/exception.py:128
#, python-format
msgid ""
"Metadata definition namespace %(namespace)s is protected and cannot be "
"deleted."
msgstr ""
"Metadata definition namespace %(namespace)s is protected and cannot be "
"deleted."

#: glance/common/exception.py:133
#, python-format
msgid ""
"Metadata definition property %(property_name)s is protected and cannot be "
"deleted."
msgstr ""
"Metadata definition property %(property_name)s is protected and cannot be "
"deleted."

#: glance/common/exception.py:138
#, python-format
msgid ""
"Metadata definition object %(object_name)s is protected and cannot be "
"deleted."
msgstr ""
"Metadata definition object %(object_name)s is protected and cannot be "
"deleted."

#: glance/common/exception.py:143
#, python-format
msgid ""
"Metadata definition resource-type-association %(resource_type)s is protected "
"and cannot be deleted."
msgstr ""
"Metadata definition resource-type-association %(resource_type)s is protected "
"and cannot be deleted."

#: glance/common/exception.py:148
#, python-format
msgid ""
"Metadata definition resource-type %(resource_type_name)s is a seeded-system "
"type and cannot be deleted."
msgstr ""
"Metadata definition resource-type %(resource_type_name)s is a seeded-system "
"type and cannot be deleted."

#: glance/common/exception.py:153
#, python-format
msgid ""
"Metadata definition tag %(tag_name)s is protected and cannot be deleted."
msgstr ""
"Metadata definition tag %(tag_name)s is protected and cannot be deleted."

#: glance/common/exception.py:134
msgid "Data supplied was not valid."
msgstr "Data supplied was not valid."

#: glance/common/exception.py:138
#: glance/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr "The supplied sort key was not valid."

#: glance/common/exception.py:166
msgid "Sort direction supplied was not valid."
msgstr "Sort direction supplied was not valid."

#: glance/common/exception.py:142
msgid "Invalid configuration in property protection file."
msgstr "Invalid configuration in property protection file."

#: glance/common/exception.py:174
msgid "Invalid configuration in glance-swift conf file."
msgstr "Invalid configuration in glance-swift conf file."

#: glance/common/exception.py:178
msgid "Unable to filter using the specified operator."
msgstr "Unable to filter using the specified operator."

#: glance/common/exception.py:146
msgid "Unable to filter using the specified range."
msgstr "Unable to filter using the specified range."

#: glance/common/exception.py:186
#, python-format
msgid "Invalid value for option %(option)s: %(value)s"
msgstr "Invalid value for option %(option)s: %(value)s"

#: glance/common/exception.py:150
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "Attribute '%(property)s' is read-only."

#: glance/common/exception.py:154
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "Attribute '%(property)s' is reserved."

#: glance/common/exception.py:158
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "Redirecting to %(uri)s for authorisation."

#: glance/common/exception.py:162
msgid "There was an error connecting to a server"
msgstr "There was an error connecting to a server"

#: glance/common/exception.py:166
msgid "There was an error configuring the client."
msgstr "There was an error configuring the client."

#: glance/common/exception.py:170
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that you "
"have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"The request returned a 302 Multiple Choices. This generally means that you "
"have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"

#: glance/common/exception.py:176
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means "
"that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned a 413 Request Entity Too Large. This generally means "
"that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:227
msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."

#: glance/common/exception.py:198
msgid "The request returned 500 Internal Server Error."
msgstr "The request returned 500 Internal Server Error."

#: glance/common/exception.py:202
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:207
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "Invalid content type %(content_type)s"

#: glance/common/exception.py:211
#, python-format
msgid ""
"Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""
"Registry was not configured correctly on API server. Reason: %(reason)s"

#: glance/common/exception.py:221
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""
"Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s"

#: glance/common/exception.py:243
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "Maximum redirects (%(redirects)s) was exceeded."

#: glance/common/exception.py:247
msgid "Received invalid HTTP redirect."
msgstr "Received invalid HTTP redirect."

#: glance/common/exception.py:251
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Response from Keystone does not contain a Glance endpoint."

#: glance/common/exception.py:255
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally means "
"that a region is required and you have not supplied one."
msgstr ""
"Multiple 'image' service matches for region %(region)s. This generally means "
"that a region is required and you have not supplied one."

#: glance/common/exception.py:261
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "Server worker creation failed: %(reason)s."

#: glance/common/exception.py:265
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "Unable to load schema: %(reason)s"

#: glance/common/exception.py:269
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "Provided object does not match schema '%(schema)s': %(reason)s"

#: glance/common/exception.py:283
msgid "The provided image is too large."
msgstr "The provided image is too large."

#: glance/common/exception.py:293
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"

#: glance/common/exception.py:298
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. Attempted: "
"%(attempted)s, Maximum: %(maximum)s"
msgstr ""
"The limit has been exceeded on the number of allowed image tags. Attempted: "
"%(attempted)s, Maximum: %(maximum)s"

#: glance/common/exception.py:303
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"

#: glance/common/exception.py:317
msgid "System SIGHUP signal received."
msgstr "System SIGHUP signal received."

#: glance/common/exception.py:308
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr "%(cls)s exception was raised in the last rpc call: %(val)s"

#: glance/common/exception.py:312
msgid "An unknown task exception occurred"
msgstr "An unknown task exception occurred"

#: glance/common/exception.py:329
msgid "Task was not configured properly"
msgstr "Task was not configured properly"

#: glance/common/exception.py:333
#, python-format
msgid "Image with the given id %(image_id)s was not found"
msgstr "Image with the given id %(image_id)s was not found"

#: glance/common/exception.py:316
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr "Task with the given id %(task_id)s was not found"

#: glance/common/exception.py:320
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr "Provided status of task is unsupported: %(status)s"

#: glance/common/exception.py:324
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr "Provided type of task is unsupported: %(type)s"

#: glance/common/exception.py:328
#, python-format
msgid ""
"Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""
"Status transition from %(cur_status)s to %(new_status)s is not allowed"

#: glance/common/exception.py:354
msgid "An import task exception occurred"
msgstr "An import task exception occurred"

#: glance/common/exception.py:333
#, python-format
msgid "The location %(location)s already exists"
msgstr "The location %(location)s already exists"

#: glance/common/exception.py:341
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"

#: glance/common/exception.py:346
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""
"Image status transition from %(cur_status)s to %(new_status)s is not allowed"

#: glance/common/exception.py:372
#, python-format
msgid "The metadata definition namespace=%(namespace_name)s already exists."
msgstr "The metadata definition namespace=%(namespace_name)s already exists."

#: glance/common/exception.py:377
#, python-format
msgid ""
"A metadata definition object with name=%(object_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"A metadata definition object with name=%(object_name)s already exists in "
"namespace=%(namespace_name)s."

#: glance/common/exception.py:382
#, python-format
msgid ""
"A metadata definition property with name=%(property_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"A metadata definition property with name=%(property_name)s already exists in "
"namespace=%(namespace_name)s."

#: glance/common/exception.py:387
#, python-format
msgid ""
"A metadata definition resource-type with name=%(resource_type_name)s already "
"exists."
msgstr ""
"A metadata definition resource-type with name=%(resource_type_name)s already "
"exists."

#: glance/common/exception.py:392
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s already exists."
msgstr ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s already exists."

#: glance/common/exception.py:399
#, python-format
msgid ""
"A metadata tag with name=%(name)s already exists in "
"namespace=%(namespace_name)s. (Please note that metadata tag names are case "
"insensitive)."
msgstr ""
"A metadata tag with name=%(name)s already exists in "
"namespace=%(namespace_name)s. (Please note that metadata tag names are case "
"insensitive)."

#: glance/common/exception.py:410
#, python-format
msgid ""
"The metadata definition %(record_type)s with name=%(record_name)s not "
"deleted. Other records still refer to it."
msgstr ""
"The metadata definition %(record_type)s with name=%(record_name)s not "
"deleted. Other records still refer to it."

#: glance/common/exception.py:416
#, python-format
msgid "Metadata definition namespace=%(namespace_name)s was not found."
msgstr "Metadata definition namespace=%(namespace_name)s was not found."

#: glance/common/exception.py:421
#, python-format
msgid ""
"The metadata definition object with name=%(object_name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"The metadata definition object with name=%(object_name)s was not found in "
"namespace=%(namespace_name)s."

#: glance/common/exception.py:427
#, python-format
msgid ""
"The metadata definition property with name=%(property_name)s was not found "
"in namespace=%(namespace_name)s."
msgstr ""
"The metadata definition property with name=%(property_name)s was not found "
"in namespace=%(namespace_name)s."

#: glance/common/exception.py:433
#, python-format
msgid ""
"The metadata definition resource-type with name=%(resource_type_name)s, was "
"not found."
msgstr ""
"The metadata definition resource-type with name=%(resource_type_name)s, was "
"not found."

#: glance/common/exception.py:438
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s, was not found."
msgstr ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s, was not found."

#: glance/common/exception.py:445
#, python-format
msgid ""
"The metadata definition tag with name=%(name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"The metadata definition tag with name=%(name)s was not found in "
"namespace=%(namespace_name)s."

#: glance/common/exception.py:451
#, python-format
msgid "Unable to verify signature: %(reason)s"
msgstr "Unable to verify signature: %(reason)s"

#: glance/common/exception.py:455
#, python-format
msgid "Version is invalid: %(reason)s"
msgstr "Version is invalid: %(reason)s"

#: glance/common/exception.py:459
msgid "Invalid property definition"
msgstr "Invalid property definition"

#: glance/common/exception.py:463
msgid "Invalid type definition"
msgstr "Invalid type definition"

#: glance/common/exception.py:467
#, python-format
msgid "Property '%(name)s' may not have value '%(val)s': %(msg)s"
msgstr "Property '%(name)s' may not have value '%(val)s': %(msg)s"

#: glance/common/exception.py:477
#, python-format
msgid "Artifact with id=%(id)s was not found"
msgstr "Artifact with id=%(id)s was not found"

#: glance/common/exception.py:481
#, python-format
msgid "Artifact with id=%(id)s is not accessible"
msgstr "Artifact with id=%(id)s is not accessible"

#: glance/common/exception.py:485
msgid "Artifact with the specified type, name and version already exists"
msgstr "Artifact with the specified type, name and version already exists"

#: glance/common/exception.py:490
#, python-format
msgid "Artifact cannot change state from %(source)s to %(target)s"
msgstr "Artifact cannot change state from %(source)s to %(target)s"

#: glance/common/exception.py:494
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the direct "
"dependency=%(dep)s"
msgstr ""
"Artifact with the specified type, name and version already has the direct "
"dependency=%(dep)s"

#: glance/common/exception.py:499
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the "
"transitive dependency=%(dep)s"
msgstr ""
"Artifact with the specified type, name and version already has the "
"transitive dependency=%(dep)s"

#: glance/common/exception.py:504
msgid "Artifact with a circular dependency can not be created"
msgstr "Artifact with a circular dependency cannot be created"

#: glance/common/exception.py:508
#, python-format
msgid "Operator %(op)s is not supported"
msgstr "Operator %(op)s is not supported"

#: glance/common/exception.py:512
#, python-format
msgid "Show level %(shl)s is not supported in this operation"
msgstr "Show level %(shl)s is not supported in this operation"

#: glance/common/exception.py:516
#, python-format
msgid "Property's %(prop)s value has not been found"
msgstr "Property's %(prop)s value has not been found"

#: glance/common/exception.py:520
#, python-format
msgid "Artifact has no property %(prop)s"
msgstr "Artifact has no property %(prop)s"

#: glance/common/exception.py:524
#, python-format
msgid "Cannot use this parameter with the operator %(op)s"
msgstr "Cannot use this parameter with the operator %(op)s"

#: glance/common/exception.py:528
#, python-format
msgid "Cannot load artifact '%(name)s'"
msgstr "Cannot load artifact '%(name)s'"

#: glance/common/exception.py:532
#, python-format
msgid "Plugin name '%(plugin)s' should match artifact typename '%(name)s'"
msgstr "Plugin name '%(plugin)s' should match artifact typename '%(name)s'"

#: glance/common/exception.py:537
#, python-format
msgid "No plugin for '%(name)s' has been loaded"
msgstr "No plugin for '%(name)s' has been loaded"

#: glance/common/exception.py:541
#, python-format
msgid ""
"Artifact type with name '%(name)s' and version '%(version)s' is not known"
msgstr ""
"Artifact type with name '%(name)s' and version '%(version)s' is not known"

#: glance/common/exception.py:546
#, python-format
msgid "Artifact state cannot be changed from %(curr)s to %(to)s"
msgstr "Artifact state cannot be changed from %(curr)s to %(to)s"

#: glance/common/exception.py:550
msgid "Invalid jsonpatch request"
msgstr "Invalid jsonpatch request"

#: glance/common/exception.py:554
#, python-format
msgid "The provided body %(body)s is invalid under given schema: %(schema)s"
msgstr "The provided body %(body)s is invalid under given schema: %(schema)s"

#: glance/common/exception.py:559
#, python-format
msgid "The provided path '%(path)s' is invalid: %(explanation)s"
msgstr "The provided path '%(path)s' is invalid: %(explanation)s"

#: glance/common/jsonpatchvalidator.py:103
msgid ""
"Json path should start with a '/', end with no '/', no 2 subsequent '/' are "
"allowed."
msgstr ""
"Json path should start with a '/', end with no '/', no 2 subsequent '/' are "
"allowed."

#: glance/common/jsonpatchvalidator.py:107
msgid ""
"Pointer contains '~' which is not part of a recognized escape sequence [~0, "
"~1]."
msgstr ""
"Pointer contains '~' which is not part of a recognised escape sequence [~0, "
"~1]."

#: glance/common/property_utils.py:31
msgid ""
"The location of the property protection file.This file contains the rules "
"for property protections and the roles/policies associated with it. If this "
"config value is not specified, by default, property protections won't be "
"enforced. If a value is specified and the file is not found, then the glance-"
"api service will not start."
msgstr ""
"The location of the property protection file. This file contains the rules "
"for property protections and the roles/policies associated with it. If this "
"config value is not specified, by default, property protections won't be "
"enforced. If a value is specified and the file is not found, then the glance-"
"api service will not start."

#: glance/common/property_utils.py:40
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in "
"the property protection file."
msgstr ""
"This config value indicates whether \"roles\" or \"policies\" are used in "
"the property protection file."

#: glance/common/property_utils.py:127
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."

#: glance/common/rpc.py:139
msgid "Request must be a list of commands"
msgstr "Request must be a list of commands"

#: glance/common/rpc.py:144
#, python-format
msgid "Bad Command: %s"
msgstr "Bad Command: %s"

#: glance/common/rpc.py:151
#, python-format
msgid "Wrong command structure: %s"
msgstr "Wrong command structure: %s"

#: glance/common/rpc.py:160
msgid "Command not found"
msgstr "Command not found"

#: glance/common/semver_db.py:77
#, python-format
msgid "Version component is too large (%d max)"
msgstr "Version component is too large (%d max)"

#: glance/common/semver_db.py:125
#, python-format
msgid "Prerelease numeric component is too large (%d characters max)"
msgstr "Prerelease numeric component is too large (%d characters max)"

#: glance/common/signature_utils.py:138
#, python-format
msgid "Invalid signature key type: %s"
msgstr "Invalid signature key type: %s"

#: glance/common/signature_utils.py:161
#, python-format
msgid "Invalid mask_gen_algorithm: %s"
msgstr "Invalid mask_gen_algorithm: %s"

#: glance/common/signature_utils.py:174
#, python-format
msgid "Invalid pss_salt_length: %s"
msgstr "Invalid pss_salt_length: %s"

#: glance/common/signature_utils.py:261 glance/common/signature_utils.py:335
msgid ""
"Required image properties for signature verification do not exist. Cannot "
"verify signature."
msgstr ""
"Required image properties for signature verification do not exist. Cannot "
"verify signature."

#: glance/common/signature_utils.py:285 glance/common/signature_utils.py:361
msgid ""
"Unable to verify signature since the algorithm is unsupported on this system"
msgstr ""
"Unable to verify signature since the algorithm is unsupported on this system"

#: glance/common/signature_utils.py:294
msgid "Error occurred while creating the verifier"
msgstr "Error occurred while creating the verifier"

#: glance/common/signature_utils.py:373
msgid "Signature verification failed."
msgstr "Signature verification failed."

#: glance/common/signature_utils.py:378
msgid "Error occurred while verifying the signature"
msgstr "Error occurred while verifying the signature"

#: glance/common/signature_utils.py:394
msgid "The signature data was not properly encoded using base64"
msgstr "The signature data was not properly encoded using base64"

#: glance/common/signature_utils.py:410
#, python-format
msgid "Invalid signature hash method: %s"
msgstr "Invalid signature hash method: %s"

#: glance/common/signature_utils.py:436
#, python-format
msgid "Invalid public key type for signature key type: %s"
msgstr "Invalid public key type for signature key type: %s"

#: glance/common/signature_utils.py:467
#, python-format
msgid "Unable to retrieve certificate with ID: %s"
msgstr "Unable to retrieve certificate with ID: %s"

#: glance/common/signature_utils.py:473
#, python-format
msgid "Invalid certificate format: %s"
msgstr "Invalid certificate format: %s"

#: glance/common/signature_utils.py:483
#, python-format
msgid "Certificate format not supported: %s"
msgstr "Certificate format not supported: %s"

#: glance/common/signature_utils.py:505
#, python-format
msgid "Certificate is not valid before: %s UTC"
msgstr "Certificate is not valid before: %s UTC"

#: glance/common/signature_utils.py:510
#, python-format
msgid "Certificate is not valid after: %s UTC"
msgstr "Certificate is not valid after: %s UTC"

#: glance/common/swift_store_utils.py:25
msgid ""
"The reference to the default swift account/backing store parameters to use "
"for adding new images."
msgstr ""
"The reference to the default swift account/backing store parameters to use "
"for adding new images."

#: glance/common/swift_store_utils.py:28
msgid ""
"The address where the Swift authentication service is listening.(deprecated)"
msgstr ""
"The address where the Swift authentication service is listening.(deprecated)"

#: glance/common/swift_store_utils.py:31
msgid ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"
msgstr ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"

#: glance/common/swift_store_utils.py:34
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"
msgstr ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"

#: glance/common/swift_store_utils.py:37
msgid "The config file that has the swift account(s)configs."
msgstr "The config file that has the swift account(s)configs."

#: glance/common/utils.py:251
#, python-format
msgid "Bad header: %(header_name)s"
msgstr "Bad header: %(header_name)s"

#: glance/common/utils.py:261
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr "Cannot convert image %(key)s '%(value)s' to an integer."

#: glance/common/utils.py:313
msgid "Cannot be a negative value."
msgstr "Cannot be a negative value."

#: glance/common/utils.py:509
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it.  Error: %(ioe)s"
msgstr ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it.  Error: %(ioe)s"

#: glance/common/utils.py:516
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it. OpenSSL error: %(ce)s"
msgstr ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it. OpenSSL error: %(ce)s"

#: glance/common/utils.py:530
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"

#: glance/common/utils.py:480
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr "Host and port \"%s\" is not valid."

#: glance/common/utils.py:483
#, python-format
msgid "Port \"%s\" is not valid."
msgstr "Port \"%s\" is not valid."

#: glance/common/utils.py:492
#, python-format
msgid "Host \"%s\" is not valid."
msgstr "Host \"%s\" is not valid."

#: glance/common/utils.py:495
#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in brackets "
"separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in brackets "
"separately from the port (i.e., \"[fe80::a:b:c]:9876\")."

#: glance/common/utils.py:530
msgid "Property names can't contain 4 byte unicode."
msgstr "Property names can't contain 4 byte Unicode."

#: glance/common/utils.py:533
#, python-format
msgid "%s can't contain 4 byte unicode characters."
msgstr "%s can't contain 4 byte unicode characters."

#: glance/common/utils.py:542
msgid "Param values can't contain 4 byte unicode."
msgstr "Param values can't contain 4 byte Unicode."

#: glance/common/utils.py:562
#, python-format
msgid "Value %(value)d out of range, must not exceed %(max)d"
msgstr "Value %(value)d out of range, must not exceed %(max)d"

#: glance/common/utils.py:570
#, python-format
msgid "'%(param)s' value out of range, must not exceed %(max)d"
msgstr "'%(param)s' value out of range, must not exceed %(max)d"

#: glance/common/utils.py:627
#, python-format
msgid ""
"Invalid filter value %s. There is no comma before opening quotation mark."
msgstr ""
"Invalid filter value %s. There is no comma before opening quotation mark."

#: glance/common/utils.py:632
#, python-format
msgid ""
"Invalid filter value %s. There is no comma after closing quotation mark."
msgstr ""
"Invalid filter value %s. There is no comma after closing quotation mark."

#: glance/common/utils.py:637
#, python-format
msgid "Invalid filter value %s. The quote is not closed."
msgstr "Invalid filter value %s. The quote is not closed."

#: glance/common/utils.py:687
msgid "Unable to filter on a unknown operator."
msgstr "Unable to filter on a unknown operator."

#: glance/common/wsgi.py:53
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."

#: glance/common/wsgi.py:56
msgid "The port on which the server will listen."
msgstr "The port on which the server will listen."

#: glance/common/wsgi.py:61
msgid ""
"The backlog value that will be used when creating the TCP listener socket."
msgstr ""
"The backlog value that will be used when creating the TCP listener socket."

#: glance/common/wsgi.py:64
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in seconds "
"that the connection must be idle before TCP starts sending keepalive probes."
msgstr ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in seconds "
"that the connection must be idle before TCP starts sending keepalive probes."

#: glance/common/wsgi.py:67
msgid "CA certificate file to use to verify connecting clients."
msgstr "CA certificate file to use to verify connecting clients."

#: glance/common/wsgi.py:69
msgid "Certificate file to use when starting API server securely."
msgstr "Certificate file to use when starting API server securely."

#: glance/common/wsgi.py:71
msgid "Private key file to use when starting API server securely."
msgstr "Private key file to use when starting API server securely."

#: glance/common/wsgi.py:83
msgid ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."
msgstr ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."

#: glance/common/wsgi.py:85
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated by "
"the Keystone v3 API with big service catalogs"
msgstr ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated by "
"the Keystone v3 API with big service catalogues"

#: glance/common/wsgi.py:92
msgid ""
"If False, server will return the header \"Connection: close\", If True, "
"server will return \"Connection: Keep-Alive\" in its responses. In order to "
"close the client socket connection explicitly after the response is sent and "
"read successfully by the client, you simply have to set this option to False "
"when you create a wsgi server."
msgstr ""
"If False, server will return the header \"Connection: close\". If True, "
"server will return \"Connection: Keep-Alive\" in its responses. In order to "
"close the client socket connection explicitly after the response is sent and "
"read successfully by the client, you simply have to set this option to False "
"when you create a wsgi server."

#: glance/common/wsgi.py:101
msgid ""
"Timeout for client connections' socket operations. If an incoming connection "
"is idle for this number of seconds it will be closed. A value of '0' means "
"wait forever."
msgstr ""
"Timeout for client connections' socket operations. If an incoming connection "
"is idle for this number of seconds, it will be closed. A value of '0' means "
"'wait forever'."

#: glance/common/wsgi.py:109
msgid ""
"The HTTP header used to determine the scheme for the original request, even "
"if it was removed by an SSL terminating proxy. Typical value is "
"\"HTTP_X_FORWARDED_PROTO\"."
msgstr ""
"The HTTP header used to determine the scheme for the original request, even "
"if it was removed by an SSL terminating proxy. Typical value is "
"\"HTTP_X_FORWARDED_PROTO\"."

#: glance/common/wsgi.py:117
msgid "If False fully disable profiling feature."
msgstr "If False, fully disable profiling feature."

#: glance/common/wsgi.py:119
msgid "If False doesn't trace SQL requests."
msgstr "If False, SQL requests won't be traced."

#: glance/common/wsgi.py:121
msgid ""
"Secret key to use to sign Glance API and Glance Registry services tracing "
"messages."
msgstr ""
"Secret key to use to sign Glance API and Glance Registry services tracing "
"messages."

#: glance/common/wsgi.py:131
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"

#: glance/common/wsgi.py:169
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr "Could not bind to %(host)s:%(port)s after trying for 30 seconds"

#: glance/common/wsgi.py:233
msgid "eventlet 'poll' nor 'selects' hubs are available on this platform"
msgstr "eventlet 'poll' nor 'selects' hubs are available on this platform"

#: glance/common/wsgi.py:786
#, python-format
msgid "Malformed Content-Range header: %s"
msgstr "Malformed Content-Range header: %s"

#: glance/common/wsgi.py:819
msgid "Unexpected body type. Expected list/dict."
msgstr "Unexpected body type. Expected list/dict."

#: glance/common/wsgi.py:552
msgid "Malformed JSON in request body."
msgstr "Malformed JSON in request body."

#: glance/common/wsgi.py:912
msgid "A body is not expected with this request."
msgstr "A body is not expected with this request."

#: glance/common/wsgi.py:924
msgid ""
"Error decoding your request. Either the URL or the request body contained "
"characters that could not be decoded by Glance"
msgstr ""
"Error decoding your request. Either the URL or the request body contained "
"characters that could not be decoded by Glance"

#: glance/common/glare/declarative.py:59
msgid "Not a valid value type"
msgstr "Not a valid value type"

#: glance/common/glare/declarative.py:92
msgid "Default value is invalid"
msgstr "Default value is invalid"

#: glance/common/glare/declarative.py:106
#: glance/common/glare/declarative.py:712
msgid "Value is required"
msgstr "Value is required"

#: glance/common/glare/declarative.py:129
msgid "Invalid item type specification"
msgstr "Invalid item type specification"

#: glance/common/glare/declarative.py:132
msgid "List definitions may hot have defaults"
msgstr "List definitions may hot have defaults"

#: glance/common/glare/declarative.py:147
msgid "Cannot specify 'min_size' explicitly"
msgstr "Cannot specify 'min_size' explicitly"

#: glance/common/glare/declarative.py:152
msgid "Cannot specify 'max_size' explicitly"
msgstr "Cannot specify 'max_size' explicitly"

#: glance/common/glare/declarative.py:177
msgid "List size is less than minimum"
msgstr "List size is less than minimum"

#: glance/common/glare/declarative.py:186
msgid "List size is greater than maximum"
msgstr "List size is greater than maximum"

#: glance/common/glare/declarative.py:201
msgid "Items have to be unique"
msgstr "Items have to be unique"

#: glance/common/glare/declarative.py:249
msgid "Invalid dict property type specification"
msgstr "Invalid dict property type specification"

#: glance/common/glare/declarative.py:255
msgid "Invalid dict property type"
msgstr "Invalid dict property type"

#: glance/common/glare/declarative.py:269
msgid "Dictionary contains unexpected key(s)"
msgstr "Dictionary contains unexpected key(s)"

#: glance/common/glare/declarative.py:285
msgid "Dictionary size is less than minimum"
msgstr "Dictionary size is less than minimum"

#: glance/common/glare/declarative.py:295
msgid "Dictionary size is greater than maximum"
msgstr "Dictionary size is greater than maximum"

#: glance/common/glare/declarative.py:362
msgid "Custom validators list should contain tuples '(function, message)'"
msgstr "Custom validators list should contain tuples '(function, message)'"

#: glance/common/glare/declarative.py:379
#, python-format
msgid "Allowed values %s are invalid under given validators"
msgstr "Allowed values %s are invalid under given validators"

#: glance/common/glare/declarative.py:386
msgid "Is not allowed value"
msgstr "Is not allowed value"

#: glance/common/glare/declarative.py:404
msgid "Dependency relations cannot be mutable"
msgstr "Dependency relations cannot be mutable"

#: glance/common/glare/declarative.py:463
msgid "Attempt to set readonly property"
msgstr "Attempt to set readonly property"

#: glance/common/glare/declarative.py:471
msgid "Attempt to set value of immutable property"
msgstr "Attempt to set value of immutable property"

#: glance/common/glare/declarative.py:557
msgid "Type version has to be a valid semver string"
msgstr "Type version has to be a valid semver string"

#: glance/common/glare/declarative.py:565
#, python-format
msgid "%(attribute)s is required"
msgstr "%(attribute)s is required"

#: glance/common/glare/declarative.py:570
#, python-format
msgid "%(attribute)s have to be string"
msgstr "%(attribute)s have to be string"

#: glance/common/glare/declarative.py:573
#, python-format
msgid "%(attribute)s may not be longer than %(length)i"
msgstr "%(attribute)s may not be longer than %(length)i"

#: glance/common/glare/declarative.py:577
#, python-format
msgid "%(attribute)s may not be shorter than %(length)i"
msgstr "%(attribute)s may not be shorter than %(length)i"

#: glance/common/glare/declarative.py:581
#, python-format
msgid "%(attribute)s should match pattern %(pattern)s"
msgstr "%(attribute)s should match pattern %(pattern)s"

#: glance/common/glare/declarative.py:625
msgid "Cannot declare artifact property with reserved name 'metadata'"
msgstr "Cannot declare artifact property with reserved name 'metadata'"

#: glance/common/glare/declarative.py:654
msgid "Unable to modify collection in immutable or readonly property"
msgstr "Unable to modify collection in immutable or readonly property"

#: glance/common/glare/definitions.py:71
msgid "Max string length may not exceed 255 characters"
msgstr "Max string length may not exceed 255 characters"

#: glance/common/glare/definitions.py:74
msgid "Length  is greater than maximum"
msgstr "Length  is greater than maximum"

#: glance/common/glare/definitions.py:85
msgid "Min string length may not be negative"
msgstr "Min string length may not be negative"

#: glance/common/glare/definitions.py:89
msgid "Length is less than minimum"
msgstr "Length is less than minimum"

#: glance/common/glare/definitions.py:101
msgid "Does not match pattern"
msgstr "Does not match pattern"

#: glance/common/glare/definitions.py:158
#: glance/common/glare/definitions.py:210
#: glance/common/glare/definitions.py:260
msgid "Value is less than minimum"
msgstr "Value is less than minimum"

#: glance/common/glare/definitions.py:169
#: glance/common/glare/definitions.py:221
#: glance/common/glare/definitions.py:271
msgid "Value is greater than maximum"
msgstr "Value is greater than maximum"

#: glance/common/glare/definitions.py:312
msgid "Array property can't have item_type=Array"
msgstr "Array property can't have item_type=Array"

#: glance/common/glare/definitions.py:384
msgid "Unable to specify artifact type explicitly"
msgstr "Unable to specify artifact type explicitly"

#: glance/common/glare/definitions.py:387
msgid "Unable to specify artifact type version explicitly"
msgstr "Unable to specify artifact type version explicitly"

#: glance/common/glare/definitions.py:426
msgid "Unable to specify version if multiple types are possible"
msgstr "Unable to specify version if multiple types are possible"

#: glance/common/glare/definitions.py:441
msgid "Invalid referenced type"
msgstr "Invalid referenced type"

#: glance/common/glare/definitions.py:444
msgid "Unable to specify version if type is not specified"
msgstr "Unable to specify version if type is not specified"

#: glance/common/glare/definitions.py:462
msgid "Invalid reference list specification"
msgstr "Invalid reference list specification"

#: glance/common/glare/definitions.py:522
msgid "BinaryObject property cannot be declared mutable"
msgstr "BinaryObject property cannot be declared mutable"

#: glance/common/glare/definitions.py:532
msgid "Blob size is not set"
msgstr "Blob size is not set"

#: glance/common/glare/definitions.py:536
msgid "File too large"
msgstr "File too large"

#: glance/common/glare/definitions.py:540
msgid "File too small"
msgstr "File too small"

#: glance/common/glare/definitions.py:545
msgid "Too few locations"
msgstr "Too few locations"

#: glance/common/glare/definitions.py:550
msgid "Too many locations"
msgstr "Too many locations"

#: glance/common/glare/loader.py:31
msgid ""
"When false, no artifacts can be loaded regardless of available_plugins. When "
"true, artifacts can be loaded."
msgstr ""
"When false, no artifacts can be loaded regardless of available_plugins. When "
"true, artifacts can be loaded."

#: glance/common/glare/loader.py:35
msgid ""
"A list of artifacts that are allowed in the format name or name-version. "
"Empty list means that any artifact can be loaded."
msgstr ""
"A list of artifacts that are allowed in the format name or name-version. "
"Empty list means that any artifact can be loaded."

#: glance/common/glare/serialization.py:192
#, python-format
msgid "Blob %(name)s may not have multiple values"
msgstr "Blob %(name)s may not have multiple values"

#: glance/common/glare/serialization.py:213
#, python-format
msgid "Relation %(name)s may not have multiple values"
msgstr "Relation %(name)s may not have multiple values"

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image location "
"order. Currently two strategies are packaged with Glance 'location_order' "
"and 'store_type'."
msgstr ""
"This value sets what strategy will be used to determine the image location "
"order. Currently two strategies are packaged with Glance 'location_order' "
"and 'store_type'."

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being used."
msgstr ""
"%(strategy)s is registered as a module twice. %(module)s is not being used."

#: glance/common/location_strategy/__init__.py:74
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"

#: glance/common/location_strategy/store_type.py:28
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'stores' config option. This "
"option will be applied when you using 'store_type' option as image location "
"strategy defined by the 'location_strategy' config option."
msgstr ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'stores' config option. This "
"option will be applied when you using 'store_type' option as image location "
"strategy defined by the 'location_strategy' config option."

#: glance/common/scripts/utils.py:61
#, python-format
msgid "Input does not contain '%(key)s' field"
msgstr "Input does not contain '%(key)s' field"

#: glance/common/scripts/utils.py:95
msgid ""
"File based imports are not allowed. Please use a non-local source of image "
"data."
msgstr ""
"File based imports are not allowed. Please use a non-local source of image "
"data."

#: glance/common/scripts/utils.py:104
#, python-format
msgid ""
"The given uri is not valid. Please specify a valid uri from the following "
"list of supported uri %(supported)s"
msgstr ""
"The given URI is not valid. Please specify a valid URI from the following "
"list of supported URI %(supported)s"

#: glance/common/scripts/image_import/main.py:103
#, python-format
msgid ""
"The Image %(image_id)s object being created by this task %(task_id)s, is no "
"longer in valid status for further processing."
msgstr ""
"The Image %(image_id)s object being created by this task %(task_id)s, is no "
"longer in valid status for further processing."

#: glance/contrib/plugins/image_artifact/v2/image.py:44
msgid "Either a file or a legacy_image_id has to be specified"
msgstr "Either a file or a legacy_image_id has to be specified"

#: glance/contrib/plugins/image_artifact/v2/image.py:49
msgid "Both file and legacy_image_id may not be specified at the same time"
msgstr "Both file and legacy_image_id may not be specified at the same time"

#: glance/contrib/plugins/image_artifact/v2/image.py:59
msgid "Glance client not installed"
msgstr "Glance client not installed"

#: glance/contrib/plugins/image_artifact/v2/image.py:68
msgid "Unable to get legacy image"
msgstr "Unable to get legacy image"

#: glance/contrib/plugins/image_artifact/v2/image.py:82
msgid "Legacy image was not found"
msgstr "Legacy image was not found"

#: glance/db/__init__.py:85 glance/db/__init__.py:127 glance/db/__init__.py:137
#: glance/db/__init__.py:151
#, python-format
msgid "No artifact found with ID %s"
msgstr "No artifact found with ID %s"

#: glance/db/__init__.py:64 glance/db/__init__.py:167 glance/db/__init__.py:179
#: glance/db/sqlalchemy/api.py:181
#, python-format
msgid "No image found with ID %s"
msgstr "No image found with ID %s"

#: glance/db/__init__.py:238
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."

#: glance/db/__init__.py:255
#, python-format
msgid "The specified member %s could not be found"
msgstr "The specified member %s could not be found"

#: glance/db/__init__.py:334 glance/db/__init__.py:360
#: glance/db/__init__.py:377 glance/db/simple/api.py:762
#, python-format
msgid "Could not find task %s"
msgstr "Could not find task %s"

#: glance/db/__init__.py:539
#, python-format
msgid "Could not find namespace %s"
msgstr "Could not find namespace %s"

#: glance/db/__init__.py:561 glance/db/__init__.py:571
#: glance/db/__init__.py:581 glance/db/__init__.py:591
#, python-format
msgid "The specified namespace %s could not be found"
msgstr "The specified namespace %s could not be found"

#: glance/db/__init__.py:682
#, python-format
msgid "Could not find metadata object %s"
msgstr "Could not find metadata object %s"

#: glance/db/__init__.py:705
#, python-format
msgid "The specified metadata object %s could not be found"
msgstr "The specified metadata object %s could not be found"

#: glance/db/__init__.py:798
#, python-format
msgid "The specified resource type %s could not be found "
msgstr "The specified resource type %s could not be found "

#: glance/db/__init__.py:845
#, python-format
msgid "Could not find property %s"
msgstr "Could not find property %s"

#: glance/db/__init__.py:867
#, python-format
msgid "The specified property %s could not be found"
msgstr "The specified property %s could not be found"

#: glance/db/__init__.py:931
#, python-format
msgid "Could not find metadata tag %s"
msgstr "Could not find metadata tag %s"

#: glance/db/__init__.py:957
#, python-format
msgid "The specified metadata tag %s could not be found"
msgstr "The specified metadata tag %s could not be found"

#: glance/db/simple/api.py:256 glance/db/sqlalchemy/api.py:407
msgid "Unable to filter on a range with a non-numeric value."
msgstr "Unable to filter on a range with a non-numeric value."

#: glance/db/simple/api.py:317 glance/db/sqlalchemy/api.py:525
#, python-format
msgid "Unable to filter by unknown operator '%s'."
msgstr "Unable to filter by unknown operator '%s'."

#: glance/db/simple/api.py:425 glance/db/sqlalchemy/api.py:951
msgid "Image id is required."
msgstr "Image id is required."

#: glance/db/simple/api.py:570 glance/db/sqlalchemy/api.py:873
#, python-format
msgid "The location data has an invalid ID: %d"
msgstr "The location data has an invalid ID: %d"

#: glance/db/simple/api.py:590 glance/db/simple/api.py:616
#: glance/db/sqlalchemy/api.py:893 glance/db/sqlalchemy/api.py:919
#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr "No location found with ID %(loc)s from image %(img)s"

#: glance/db/simple/api.py:600
msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'."
msgstr ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'."

#: glance/db/simple/api.py:772 glance/db/sqlalchemy/api.py:1256
#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr "Forbidding request, task %s is not visible"

#: glance/db/simple/api.py:890
msgid "Task does not exist"
msgstr "Task does not exist"

#: glance/db/simple/api.py:1155
#: glance/db/sqlalchemy/metadef_api/namespace.py:249
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition namespace "
"with the same name of %s"
msgstr ""
"Invalid update. It would result in a duplicate metadata definition namespace "
"with the same name of %s"

#: glance/db/simple/api.py:1176
#: glance/db/sqlalchemy/metadef_api/namespace.py:88
#, python-format
msgid "Metadata definition namespace not found for id=%s"
msgstr "Metadata definition namespace not found for id=%s"

#: glance/db/simple/api.py:1184 glance/db/simple/api.py:2128
#: glance/db/sqlalchemy/metadef_api/namespace.py:97
#: glance/db/sqlalchemy/metadef_api/namespace.py:119
#, python-format
msgid "Forbidding request, metadata definition namespace=%s is not visible."
msgstr "Forbidding request, metadata definition namespace=%s is not visible."

#: glance/db/simple/api.py:1307 glance/db/sqlalchemy/metadef_api/object.py:35
#, python-format
msgid "Metadata definition object not found for id=%s"
msgstr "Metadata definition object not found for id=%s"

#: glance/db/simple/api.py:1388
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s  in namespace=%(namespace_name)s."
msgstr ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s  in namespace=%(namespace_name)s."

#: glance/db/simple/api.py:1515
#: glance/db/sqlalchemy/metadef_api/property.py:122
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition property "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"Invalid update. It would result in a duplicate metadata definition property "
"with the same name=%(name)s in namespace=%(namespace_name)s."

#: glance/db/simple/api.py:1559 glance/db/sqlalchemy/metadef_api/property.py:37
#, python-format
msgid "Metadata definition property not found for id=%s"
msgstr "Metadata definition property not found for id=%s"

#: glance/db/simple/api.py:1765
#, python-format
msgid "Metadata definition tag not found for id=%s"
msgstr "Metadata definition tag not found for id=%s"

#: glance/db/sqlalchemy/api.py:85
msgid "You do not own this image"
msgstr "You do not own this image"

#: glance/db/sqlalchemy/api.py:337
#: glance/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Unknown sort direction, must be 'desc' or 'asc'"

#: glance/db/sqlalchemy/api.py:507
#, python-format
msgid "Bad \"%s\" query filter format. Use ISO 8601 DateTime notation."
msgstr "Bad \"%s\" query filter format. Use ISO 8601 DateTime notation."

#: glance/db/sqlalchemy/api.py:682
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"

#: glance/db/sqlalchemy/api.py:902
msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'"
msgstr ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'"

#: glance/db/sqlalchemy/metadata.py:42
msgid "Path to the directory where json metadata files are stored"
msgstr "Path to the directory where json metadata files are stored"

#: glance/db/sqlalchemy/metadef_api/object.py:112
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s in namespace=%(namespace_name)s."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:86
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:149
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like swift://user:pass@http://authurl.com/v1/container/obj, "
"you need to change it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like swift://user:pass@http://authurl.com/v1/container/obj, "
"you need to change it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:123
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:185
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr "Badly formed credentials '%(creds)s' in Swift URI"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:135
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:197
#: glance/store/swift.py:246
msgid "Badly formed credentials in Swift URI."
msgstr "Badly formed credentials in Swift URI."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:152
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:214
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr "Badly formed S3 URI: %(uri)s"

#: glance/domain/__init__.py:59
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr "new_image() got unexpected keywords %s"

#: glance/domain/__init__.py:129
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr "__init__() got unexpected keyword argument '%s'"

#: glance/domain/__init__.py:151
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "Property %s must be set prior to saving data."

#: glance/domain/__init__.py:154
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "Properties %s must be set prior to saving data."

#: glance/domain/__init__.py:171
msgid "Visibility must be either \"public\" or \"private\""
msgstr "Visibility must be either \"public\" or \"private\""

#: glance/domain/__init__.py:190
msgid "Attribute container_format can be only replaced for a queued image."
msgstr "Attribute container_format can be only replaced for a queued image."

#: glance/domain/__init__.py:202
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr "Attribute disk_format can be only replaced for a queued image."

#: glance/domain/__init__.py:214 glance/domain/__init__.py:227
msgid "Cannot be a negative value"
msgstr "Cannot be a negative value"

#: glance/domain/__init__.py:255
#, python-format
msgid "Not allowed to deactivate image in status '%s'"
msgstr "Not allowed to deactivate image in status '%s'"

#: glance/domain/__init__.py:268
#, python-format
msgid "Not allowed to reactivate image in status '%s'"
msgstr "Not allowed to reactivate image in status '%s'"

#: glance/domain/__init__.py:292
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "Status must be \"pending\", \"accepted\" or \"rejected\"."

#: glance/glare/dependency.py:66
#, python-format
msgid "Not all dependencies are in '%s' state"
msgstr "Not all dependencies are in '%s' state"

#: glance/glare/dependency.py:98
#, python-format
msgid "Dependency property '%s' has to be deleted first"
msgstr "Dependency property '%s' has to be deleted first"

#: glance/glare/location.py:159
#, python-format
msgid "Get blob %(name)s data failed: %(err)s."
msgstr "Get blob %(name)s data failed: %(err)s."

#: glance/glare/updater.py:52
msgid "No property to access"
msgstr "No property to access"

#: glance/glare/updater.py:130
#, python-format
msgid "Array has no element at position %d"
msgstr "Array has no element at position %d"

#: glance/glare/updater.py:134
#, python-format
msgid "Not an array idx '%s'"
msgstr "Not an array idx '%s'"

#: glance/glare/updater.py:174
#, python-format
msgid "No such key '%s' in a dict"
msgstr "No such key '%s' in a dict"

#: glance/image_cache/__init__.py:34
msgid "The driver to use for image cache management."
msgstr "The driver to use for image cache management."

#: glance/image_cache/__init__.py:39
msgid ""
"The upper limit (the maximum size of accumulated cache in bytes) beyond "
"which the cache pruner, if running, starts cleaning the image cache."
msgstr ""
"The upper limit (the maximum size of accumulated cache in bytes) beyond "
"which the cache pruner, if running, starts cleaning the image cache."

#: glance/image_cache/__init__.py:43
msgid ""
"The amount of time to let an incomplete image remain in the cache, before "
"the cache cleaner, if running, will remove the incomplete image."
msgstr ""
"The amount of time to let an incomplete image remain in the cache, before "
"the cache cleaner, if running, will remove the incomplete image."

#: glance/image_cache/__init__.py:47
msgid "Base directory that the image cache uses."
msgstr "Base directory that the image cache uses."

#: glance/image_cache/__init__.py:253
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr "Checksum verification failed. Aborted caching of image '%s'."

#: glance/image_cache/client.py:117
msgid ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"keystone authentication strategy is enabled\n"
msgstr ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"Keystone authentication strategy is enabled\n"

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr "Failed to read %s from config"

#: glance/image_cache/drivers/sqlite.py:39
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""
"The path to the sqlite file database that will be used for image cache "
"management."

#: glance/image_cache/drivers/sqlite.py:121
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr "Failed to initialise the image cache database. Got error: %s"

#: glance/image_cache/drivers/xattr.py:104
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not "
"support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the cache "
"directory."
msgstr ""
"The device housing the image cache directory %(image_cache_dir)s does not "
"support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the cache "
"directory."

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr "Address to find the registry server."

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr "Port the registry server is listening on."

#: glance/registry/api/v1/images.py:107 glance/registry/api/v1/images.py:112
msgid "Invalid marker. Image could not be found."
msgstr "Invalid marker. Image could not be found."

#: glance/registry/api/v1/images.py:216
msgid "Unrecognized changes-since value"
msgstr "Unrecognised changes-since value"

#: glance/registry/api/v1/images.py:221
msgid "protected must be True, or False"
msgstr "protected must be True, or False"

#: glance/registry/api/v1/images.py:268
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "Unsupported sort_key. Acceptable values: %s"

#: glance/registry/api/v1/images.py:277
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "Unsupported sort_dir. Acceptable values: %s"

#: glance/registry/api/v1/images.py:303
msgid "is_public must be None, True, or False"
msgstr "is_public must be None, True, or False"

#: glance/registry/api/v1/images.py:395
msgid "Invalid image id format"
msgstr "Invalid image id format"

#: glance/registry/api/v1/images.py:409
#, python-format
msgid "Image with identifier %s already exists!"
msgstr "Image with identifier %s already exists!"

#: glance/registry/api/v1/images.py:451
#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr "Failed to add image metadata. Got error: %s"

#: glance/registry/api/v1/images.py:322 glance/registry/api/v1/images.py:363
#: glance/registry/api/v1/images.py:466 glance/registry/api/v1/members.py:66
#: glance/registry/api/v1/members.py:100 glance/registry/api/v1/members.py:213
#: glance/registry/api/v1/members.py:273
#, python-format
msgid "Image %(id)s not found"
msgstr "Image %(id)s not found"

#: glance/registry/api/v1/members.py:114 glance/registry/api/v1/members.py:227
#: glance/registry/api/v1/members.py:287
msgid "No permission to share that image"
msgstr "No permission to share that image"

#: glance/registry/api/v1/members.py:125 glance/registry/api/v1/members.py:141
#: glance/registry/api/v1/members.py:240
#, python-format
msgid "Invalid membership association: %s"
msgstr "Invalid membership association: %s"

#: glance/registry/api/v1/members.py:300 glance/registry/api/v1/members.py:317
msgid "Membership could not be found."
msgstr "Membership could not be found."

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr "Registry service can't use %s"

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either http "
"or https."
msgstr ""
"The protocol to use for communication with the registry server.  Either http "
"or https."

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the key file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_KEY_FILE environment "
"variable to a filepath of the key file"
msgstr ""
"The path to the key file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_KEY_FILE environment "
"variable to a filepath of the key file"

#: glance/registry/client/__init__.py:31
msgid ""
"The path to the cert file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_CERT_FILE environment "
"variable to a filepath of the CA cert file"
msgstr ""
"The path to the cert file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_CERT_FILE environment "
"variable to a filepath of the CA cert file"

#: glance/registry/client/__init__.py:36
msgid ""
"The path to the certifying authority cert file to use in SSL connections to "
"the registry server, if any. Alternately, you may set the "
"GLANCE_CLIENT_CA_FILE environment variable to a filepath of the CA cert file."
msgstr ""
"The path to the certifying authority cert file to use in SSL connections to "
"the registry server, if any. Alternately, you may set the "
"GLANCE_CLIENT_CA_FILE environment variable to a filepath of the CA cert file."

#: glance/registry/client/__init__.py:42
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority. This is the registry's equivalent of "
"specifying --insecure on the command line using glanceclient for the API."
msgstr ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority. This is the registry's equivalent of "
"specifying --insecure on the command line using glanceclient for the API."

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a registry "
"request to complete. A value of 0 implies no timeout."
msgstr ""
"The period of time, in seconds, that the API server will wait for a registry "
"request to complete. A value of 0 implies no timeout."

#: glance/registry/client/__init__.py:64
msgid ""
"Whether to pass through the user token when making requests to the registry. "
"To prevent failures with token expiration during big files upload, it is "
"recommended to set this parameter to False.If \"use_user_token\" is not in "
"effect, then admin credentials can be specified."
msgstr ""
"Whether to pass through the user token when making requests to the registry. "
"To prevent failures with token expiration during big files upload, it is "
"recommended to set this parameter to False.If \"use_user_token\" is not in "
"effect, then admin credentials can be specified."

#: glance/registry/client/__init__.py:73
msgid ""
"The administrators user name. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"The administrators user name. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."

#: glance/registry/client/__init__.py:78
msgid ""
"The administrators password. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"The administrators password. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."

#: glance/registry/client/__init__.py:83
msgid ""
"The tenant name of the administrative user. If \"use_user_token\" is not in "
"effect, then admin tenant name can be specified."
msgstr ""
"The tenant name of the administrative user. If \"use_user_token\" is not in "
"effect, then admin tenant name can be specified."

#: glance/registry/client/__init__.py:88
msgid ""
"The URL to the keystone service. If \"use_user_token\" is not in effect and "
"using keystone auth, then URL of keystone can be specified."
msgstr ""
"The URL to the Keystone service. If \"use_user_token\" is not in effect and "
"using Keystone auth, then URL of Keystone can be specified."

#: glance/registry/client/__init__.py:94
msgid ""
"The strategy to use for authentication. If \"use_user_token\" is not in "
"effect, then auth strategy can be specified."
msgstr ""
"The strategy to use for authentication. If \"use_user_token\" is not in "
"effect, then auth strategy can be specified."

#: glance/registry/client/__init__.py:99
msgid ""
"The region for the authentication service. If \"use_user_token\" is not in "
"effect and using keystone auth, then region name can be specified."
msgstr ""
"The region for the authentication service. If \"use_user_token\" is not in "
"effect and using Keystone auth, then region name can be specified."

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr "Configuration option was not valid"

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr "Could not find required configuration option"

#: glance/tests/unit/test_migrations.py:927
#, python-format
msgid "location: %s data lost"
msgstr "location: %s data lost"
