# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
# Andi Chandler <andi@gowling.com>, 2017. #zanata
# Andi Chandler <andi@gowling.com>, 2018. #zanata
# Andi Chandler <andi@gowling.com>, 2019. #zanata
msgid ""
msgstr ""
"Project-Id-Version: keystone VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-21 07:06+0000\n"
"PO-Revision-Date: 2020-06-02 19:33+0000\n"
"Last-Translator: Andi Chandler <Unknown>\n"
"Language-Team: English (United Kingdom)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-07-09 19:28+0000\n"
"X-Generator: Launchpad (build 4809fcb62f445aaa3ae919f7f6c3cc7d156ea57a)\n"
"Language: en_GB\n"
"Generated-By: Babel 2.0\n"

#: keystone/exception.py:83
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not comply "
"with the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."
msgstr ""
"Expecting to find %(attribute)s in %(target)s - the server could not comply "
"with the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."

#: keystone/exception.py:92
#, python-format
msgid "Cannot create an endpoint with an invalid URL: %(url)s"
msgstr "Cannot create an endpoint with an invalid URL: %(url)s"

#: keystone/exception.py:99
#, python-format
msgid "%(detail)s"
msgstr "%(detail)s"

#: keystone/exception.py:103
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client is "
"assumed to be in error."
msgstr ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client is "
"assumed to be in error."

#: keystone/exception.py:112
msgid ""
"The 'expires_at' must not be before now. The server could not comply with "
"the request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""
"The 'expires_at' must not be before now. The server could not comply with "
"the request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."

#: keystone/exception.py:121
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the limit "
"of column %(type)s(CHAR(%(length)d))."
msgstr ""
"String length exceeded. The length of string '%(string)s' exceeded the limit "
"of column %(type)s(CHAR(%(length)d))."

#: keystone/exception.py:127
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. The "
"server could not comply with the request because the attribute size is "
"invalid (too large). The client is assumed to be in error."
msgstr ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. The "
"server could not comply with the request because the attribute size is "
"invalid (too large). The client is assumed to be in error."

#: keystone/exception.py:137
#, python-format
msgid ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."
msgstr ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."

#: keystone/exception.py:156
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server could "
"not comply with the request because the password is invalid."
msgstr ""
"The password length must be less than or equal to %(size)i. The server could "
"not comply with the request because the password is invalid."

#: keystone/exception.py:162
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions have "
"associated endpoints."
msgstr ""
"Unable to delete region %(region_id)s because it or its child regions have "
"associated endpoints."

#: keystone/exception.py:167
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."

#: keystone/exception.py:179
msgid "(Disable insecure_debug mode to suppress these details.)"
msgstr "(Disable insecure_debug mode to suppress these details.)"

#: keystone/exception.py:189
#, python-format
msgid "%(message)s %(amendment)s"
msgstr "%(message)s %(amendment)s"

#: keystone/exception.py:197
msgid "The request you have made requires authentication."
msgstr "The request you have made requires authentication."

#: keystone/exception.py:203
msgid "Authentication plugin error."
msgstr "Authentication plugin error."

#: keystone/exception.py:211
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr "Unable to find valid groups while using mapping %(mapping_id)s"

#: keystone/exception.py:216
msgid "Attempted to authenticate with an unsupported method."
msgstr "Attempted to authenticate with an unsupported method."

#: keystone/exception.py:224
msgid "Additional authentications steps required."
msgstr "Additional authentications steps required."

#: keystone/exception.py:232
msgid "You are not authorized to perform the requested action."
msgstr "You are not authorised to perform the requested action."

#: keystone/exception.py:239
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr "You are not authorised to perform the requested action: %(action)s"

#: keystone/exception.py:244
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target %(target)s"
msgstr ""
"Could not change immutable attribute(s) '%(attributes)s' in target %(target)s"

#: keystone/exception.py:249
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in question "
"is %(group_id)s, user is %(user_id)s"
msgstr ""
"Group membership across backend boundaries is not allowed, group in question "
"is %(group_id)s, user is %(user_id)s"

#: keystone/exception.py:255
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service or "
"Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, Service: "
"%(service_id)s, Region: %(region_id)s"
msgstr ""
"Invalid mix of entities for policy association - only Endpoint, Service or "
"Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, Service: "
"%(service_id)s, Region: %(region_id)s"

#: keystone/exception.py:262
#, python-format
msgid "Invalid domain specific configuration: %(reason)s"
msgstr "Invalid domain specific configuration: %(reason)s"

#: keystone/exception.py:266
#, python-format
msgid "Could not find: %(target)s"
msgstr "Could not find: %(target)s"

#: keystone/exception.py:272
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr "Could not find endpoint: %(endpoint_id)s"

#: keystone/exception.py:279
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr "An unhandled exception has occurred: Could not find metadata."

#: keystone/exception.py:284
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr "Could not find policy: %(policy_id)s"

#: keystone/exception.py:288
msgid "Could not find policy association"
msgstr "Could not find policy association"

#: keystone/exception.py:292
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr "Could not find role: %(role_id)s"

#: keystone/exception.py:296
#, python-format
msgid "%(prior_role_id)s does not imply %(implied_role_id)s"
msgstr "%(prior_role_id)s does not imply %(implied_role_id)s"

#: keystone/exception.py:300
#, python-format
msgid "%(role_id)s cannot be an implied roles"
msgstr "%(role_id)s cannot be an implied roles"

#: keystone/exception.py:304
#, python-format
msgid ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"
msgstr ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"

#: keystone/exception.py:310
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr "Could not find region: %(region_id)s"

#: keystone/exception.py:314
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr "Could not find service: %(service_id)s"

#: keystone/exception.py:318
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr "Could not find domain: %(domain_id)s"

#: keystone/exception.py:322
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr "Could not find project: %(project_id)s"

#: keystone/exception.py:326
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr "Cannot create project with parent: %(project_id)s"

#: keystone/exception.py:330
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr "Could not find token: %(token_id)s"

#: keystone/exception.py:334
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr "Could not find user: %(user_id)s"

#: keystone/exception.py:338
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr "Could not find group: %(group_id)s"

#: keystone/exception.py:342
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr "Could not find mapping: %(mapping_id)s"

#: keystone/exception.py:346
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr "Could not find trust: %(trust_id)s"

#: keystone/exception.py:350
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr "No remaining uses for trust: %(trust_id)s"

#: keystone/exception.py:354
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr "Could not find credential: %(credential_id)s"

#: keystone/exception.py:358
#, python-format
msgid "Could not find version: %(version)s"
msgstr "Could not find version: %(version)s"

#: keystone/exception.py:362
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr "Could not find Endpoint Group: %(endpoint_group_id)s"

#: keystone/exception.py:366
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr "Could not find Identity Provider: %(idp_id)s"

#: keystone/exception.py:370
#, python-format
msgid "Could not find Service Provider: %(sp_id)s"
msgstr "Could not find Service Provider: %(sp_id)s"

#: keystone/exception.py:374
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"

#: keystone/exception.py:385
#, python-format
msgid ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"
msgstr ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"

#: keystone/exception.py:403
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr "Conflict occurred attempting to store %(type)s - %(details)s"

#: keystone/exception.py:412
msgid ""
"An unexpected error prevented the server from fulfilling your request."
msgstr ""
"An unexpected error prevented the server from fulfilling your request."

#: keystone/exception.py:415
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"

#: keystone/exception.py:433
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr "Unable to consume trust %(trust_id)s, unable to acquire lock."

#: keystone/exception.py:438
msgid ""
"Expected signing certificates are not available on the server. Please check "
"Keystone configuration."
msgstr ""
"Expected signing certificates are not available on the server. Please check "
"Keystone configuration."

#: keystone/exception.py:444
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."

#: keystone/exception.py:449
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in the "
"backend."
msgstr ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in the "
"backend."

#: keystone/exception.py:454
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr "Error while reading metadata file, %(reason)s"

#: keystone/exception.py:458
#, python-format
msgid ""
"Local section in mapping %(mapping_id)s refers to a remote match that "
"doesn't exist (e.g. {0} in a local section)."
msgstr ""
"Local section in mapping %(mapping_id)s refers to a remote match that "
"doesn't exist (e.g. {0} in a local section)."

#: keystone/exception.py:464
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"

#: keystone/exception.py:471
msgid "The action you have requested has not been implemented."
msgstr "The action you have requested has not been implemented."

#: keystone/exception.py:478
msgid "The service you have requested is no longer available on this server."
msgstr ""
"The service you have requested is no longer available on this server."

#: keystone/exception.py:485
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr "The Keystone configuration file %(config_file)s could not be found."

#: keystone/exception.py:490
msgid ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap one."
msgstr ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap one."

#: keystone/exception.py:495
#, python-format
msgid ""
"The Keystone domain-specific configuration has specified more than one SQL "
"driver (only one is permitted): %(source)s."
msgstr ""
"The Keystone domain-specific configuration has specified more than one SQL "
"driver (only one is permitted): %(source)s."

#: keystone/exception.py:502
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration repository "
"path at %(path)s doesn't exist or isn't a directory."
msgstr ""
"%(mod_name)s doesn't provide database migrations. The migration repository "
"path at %(path)s doesn't exist or isn't a directory."

#: keystone/exception.py:509
msgid "Token version is unrecognizable or unsupported."
msgstr "Token version is unrecognisable or unsupported."

#: keystone/exception.py:514
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not have "
"xmlsec1 installed, or this is the result of misconfiguration. Reason "
"%(reason)s"
msgstr ""
"Unable to sign SAML assertion. It is likely that this server does not have "
"xmlsec1 installed, or this is the result of misconfiguration. Reason "
"%(reason)s"

#: keystone/exception.py:521
msgid ""
"No Authorization headers found, cannot proceed with OAuth related calls, if "
"running under HTTPd or Apache, ensure WSGIPassAuthorization is set to On."
msgstr ""
"No Authorisation headers found, cannot proceed with OAuth related calls, if "
"running under HTTPd or Apache, ensure WSGIPassAuthorization is set to On."

#: keystone/exception.py:528
#, python-format
msgid ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."
msgstr ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."

#: keystone/exception.py:536
#, python-format
msgid ""
"The %s extension has been moved into keystone core and as such its "
"migrations are maintained by the main keystone database control. Use the "
"command: keystone-manage db_sync"
msgstr ""
"The %s extension has been moved into keystone core and as such its "
"migrations are maintained by the main keystone database control. Use the "
"command: keystone-manage db_sync"

#: keystone/exception.py:544
#, python-format
msgid "%(driver)s is not supported driver version"
msgstr "%(driver)s is an unsupported driver version"

#: keystone/notifications.py:232
#, python-format
msgid ""
"%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""
"%(event)s is not a valid notification event, must be one of: %(actions)s"

#: keystone/notifications.py:241
#, python-format
msgid "Method not callable: %s"
msgstr "Method not callable: %s"

#: keystone/assignment/controllers.py:100 keystone/identity/controllers.py:71
#: keystone/resource/controllers.py:90
msgid "Name field is required and cannot be empty"
msgstr "Name field is required and cannot be empty"

#: keystone/assignment/controllers.py:146
#: keystone/assignment/controllers.py:163
#: keystone/assignment/controllers.py:182
msgid "User roles not supported: tenant_id required"
msgstr "User roles not supported: tenant_id required"

#: keystone/assignment/controllers.py:567
#: keystone/assignment/controllers.py:856
msgid "Specify a domain or project, not both"
msgstr "Specify a domain or project, not both"

#: keystone/assignment/controllers.py:570
msgid "Specify one of domain or project"
msgstr "Specify one of domain or project"

#: keystone/assignment/controllers.py:575
#: keystone/assignment/controllers.py:861
msgid "Specify a user or group, not both"
msgstr "Specify a user or group, not both"

#: keystone/assignment/controllers.py:578
msgid "Specify one of user or group"
msgstr "Specify one of user or group"

#: keystone/assignment/controllers.py:845
msgid ""
"Combining effective and group filter will always result in an empty list."
msgstr ""
"Combining effective and group filter will always result in an empty list."

#: keystone/assignment/controllers.py:850
msgid ""
"Combining effective, domain and inherited filters will always result in an "
"empty list."
msgstr ""
"Combining effective, domain and inherited filters will always result in an "
"empty list."

#: keystone/assignment/controllers.py:952
msgid ""
"scope.project.id must be specified if include_subtree is also specified"
msgstr ""
"scope.project.id must be specified if include_subtree is also specified"

#: keystone/assignment/core.py:77
msgid ""
"Use of the identity driver config to automatically configure the same "
"assignment driver has been deprecated, in the \"O\" release, the assignment "
"driver will need to be expicitly configured if different than the default "
"(SQL)."
msgstr ""
"Use of the identity driver config to automatically configure the same "
"assignment driver has been deprecated, in the \"O\" release, the assignment "
"driver will need to be expicitly configured if different than the default "
"(SQL)."

#: keystone/assignment/core.py:88
#, python-format
msgid ""
"Attempted automatic driver selection for assignment based upon [identity]\\"
"driver option failed since driver %s is not found. Set [assignment]/driver "
"to a valid driver in keystone config."
msgstr ""
"Attempted automatic driver selection for assignment based upon [identity]\\"
"driver option failed since driver %s is not found. Set [assignment]/driver "
"to a valid driver in keystone config."

#: keystone/assignment/core.py:179
msgid "Must specify either domain or project"
msgstr "Must specify either domain or project"

#: keystone/assignment/core.py:848
msgid "Cannot list assignments sourced from groups and filtered by user ID."
msgstr "Cannot list assignments sourced from groups and filtered by user ID."

#: keystone/assignment/core.py:1058
#, python-format
msgid "Project (%s)"
msgstr "Project (%s)"

#: keystone/assignment/core.py:1060
#, python-format
msgid "Domain (%s)"
msgstr "Domain (%s)"

#: keystone/assignment/core.py:1062
msgid "Unknown Target"
msgstr "Unknown Target"

#: keystone/assignment/core.py:1518
msgid "Update of `domain_id` is not allowed."
msgstr "Update of `domain_id` is not allowed."

#: keystone/assignment/core.py:1743
msgid "Domain specific roles are not supported in the V8 role driver"
msgstr "Domain specific roles are not supported in the V8 role driver"

#: keystone/assignment/V8_backends/sql.py:287
#: keystone/assignment/backends/sql.py:137
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr "Cannot remove role that has not been granted, %s"

#: keystone/assignment/V8_backends/sql.py:363
#: keystone/assignment/backends/sql.py:213
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr "Unexpected assignment type encountered, %s"

#: keystone/auth/controllers.py:60
#, python-format
msgid ""
"Direct import of auth plugin %(name)r is deprecated as of Liberty in favor "
"of its entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"Direct import of auth plugin %(name)r is deprecated as of Liberty in favour "
"of its entrypoint from %(namespace)r and may be removed in N."

#: keystone/auth/controllers.py:121
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has conflicting "
"values %(new)s and %(old)s"
msgstr ""
"Unable to reconcile identity attribute %(attribute)s as it has conflicting "
"values %(new)s and %(old)s"

#: keystone/auth/controllers.py:182
msgid "Domain name cannot contain reserved characters."
msgstr "Domain name cannot contain reserved characters."

#: keystone/auth/controllers.py:205
msgid "Project name cannot contain reserved characters."
msgstr "Project name cannot contain reserved characters."

#: keystone/auth/controllers.py:355 keystone/middleware/auth.py:130
msgid "Scoping to both domain and project is not allowed"
msgstr "Scoping to both domain and project is not allowed"

#: keystone/auth/controllers.py:358
msgid "Scoping to both domain and trust is not allowed"
msgstr "Scoping to both domain and trust is not allowed"

#: keystone/auth/controllers.py:361
msgid "Scoping to both project and trust is not allowed"
msgstr "Scoping to both project and trust is not allowed"

#: keystone/auth/controllers.py:530
msgid "User not found"
msgstr "User not found"

#: keystone/auth/controllers.py:644
msgid "A project-scoped token is required to produce a service catalog."
msgstr "A project-scoped token is required to produce a service catalogue."

#: keystone/auth/plugins/external.py:42
msgid "No authenticated user"
msgstr "No authenticated user"

#: keystone/auth/plugins/external.py:52
#, python-format
msgid "Unable to lookup user %s"
msgstr "Unable to lookup user %s"

#: keystone/auth/plugins/external.py:100
msgid "auth_type is not Negotiate"
msgstr "auth_type is not Negotiate"

#: keystone/auth/plugins/mapped.py:246
msgid ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must be "
"set."
msgstr ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must be "
"set."

#: keystone/auth/plugins/oauth1.py:46
msgid "Access token is expired"
msgstr "Access token is expired"

#: keystone/auth/plugins/oauth1.py:60
msgid "Could not validate the access token"
msgstr "Could not validate the access token"

#: keystone/auth/plugins/password.py:39
msgid "Invalid username or password"
msgstr "Invalid username or password"

#: keystone/auth/plugins/token.py:70 keystone/token/controllers.py:160
msgid "rescope a scoped token"
msgstr "rescope a scoped token"

#: keystone/auth/plugins/totp.py:96
msgid "Invalid username or TOTP passcode"
msgstr "Invalid username or TOTP passcode"

#: keystone/catalog/controllers.py:215
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""

#: keystone/catalog/core.py:149 keystone/common/ldap/core.py:1411
#, python-format
msgid "Duplicate ID, %s."
msgstr "Duplicate ID, %s."

#: keystone/catalog/backends/sql.py:389
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr "Endpoint %(endpoint_id)s not found in project %(project_id)s"

#: keystone/catalog/backends/sql.py:492
msgid "Endpoint Group Project Association not found"
msgstr "Endpoint Group Project Association not found"

#: keystone/cmd/cli.py:173
msgid ""
"Either --bootstrap-password argument or OS_BOOTSTRAP_PASSWORD must be set."
msgstr ""
"Either --bootstrap-password argument or OS_BOOTSTRAP_PASSWORD must be set."

#: keystone/cmd/cli.py:586
msgid "At least one option must be provided"
msgstr "At least one option must be provided"

#: keystone/cmd/cli.py:593
msgid "--all option cannot be mixed with other options"
msgstr "--all option cannot be mixed with other options"

#: keystone/cmd/cli.py:600
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr "Unknown domain '%(name)s' specified by --domain-name"

#: keystone/cmd/cli.py:679 keystone/tests/unit/test_cli.py:411
msgid ""
"At least one option must be provided, use either --all or --domain-name"
msgstr ""
"At least one option must be provided, use either --all or --domain-name"

#: keystone/cmd/cli.py:685 keystone/tests/unit/test_cli.py:427
msgid "The --all option cannot be used with the --domain-name option"
msgstr "The --all option cannot be used with the --domain-name option"

#: keystone/cmd/cli.py:710 keystone/tests/unit/test_cli.py:444
#, python-format
msgid ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."
msgstr ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."

#: keystone/cmd/cli.py:718 keystone/tests/unit/test_cli.py:385
#, python-format
msgid ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."
msgstr ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."

#: keystone/cmd/cli.py:732
#, python-format
msgid ""
"Error parsing configuration file for domain: %(domain)s, file: %(file)s."
msgstr ""
"Error parsing configuration file for domain: %(domain)s, file: %(file)s."

#: keystone/cmd/cli.py:783
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr "Unable to locate domain config directory: %s"

#: keystone/cmd/cli.py:803
msgid ""
"Unable to access the keystone database, please check it is configured "
"correctly."
msgstr ""
"Unable to access the keystone database, please check it is configured "
"correctly."

#: keystone/cmd/cli.py:866
#, python-format
msgid "Error while parsing rules %(path)s: %(err)s"
msgstr "Error while parsing rules %(path)s: %(err)s"

#: keystone/cmd/cli.py:875
#, python-format
msgid "Error while opening file %(path)s: %(err)s"
msgstr "Error while opening file %(path)s: %(err)s"

#: keystone/cmd/cli.py:885
#, python-format
msgid "Error while parsing line: '%(line)s': %(err)s"
msgstr "Error while parsing line: '%(line)s': %(err)s"

#: keystone/common/authorization.py:61 keystone/common/wsgi.py:67
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr "token reference must be a KeystoneToken type, got: %s"

#: keystone/common/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr "%s cannot be empty."

#: keystone/common/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr "%(property_name)s cannot be less than %(min_length)s characters."

#: keystone/common/clean.py:31
#, python-format
msgid ""
"%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""
"%(property_name)s should not be greater than %(max_length)s characters."

#: keystone/common/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr "%(property_name)s is not a %(display_expected_type)s"

#: keystone/common/controller.py:349 keystone/common/controller.py:377
#: keystone/identity/core.py:595 keystone/resource/core.py:1145
#, python-format
msgid "Expected dict or list: %s"
msgstr "Expected dict or list: %s"

#: keystone/common/controller.py:390
msgid "Marker could not be found"
msgstr "Marker could not be found"

#: keystone/common/controller.py:401
msgid "Invalid limit value"
msgstr "Invalid limit value"

#: keystone/common/controller.py:705
msgid "Cannot change Domain ID"
msgstr "Cannot change Domain ID"

#: keystone/common/controller.py:751
msgid ""
"You have tried to create a resource using the admin token. As this token is "
"not within a domain you must explicitly include a domain for this resource "
"to belong to."
msgstr ""
"You have tried to create a resource using the admin token. As this token is "
"not within a domain, you must explicitly include a domain for this resource "
"to belong to."

#: keystone/common/dependency.py:65
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr "Unregistered dependency: %(name)s for %(targets)s"

#: keystone/common/driver_hints.py:38
msgid ""
"Cannot truncate a driver call without hints list as first parameter after "
"self "
msgstr ""
"Cannot truncate a driver call without hints list as first parameter after "
"self "

#: keystone/common/json_home.py:76
#, python-format
msgid "Unexpected status requested for JSON Home response, %s"
msgstr "Unexpected status requested for JSON Home response, %s"

#: keystone/common/manager.py:82
#, python-format
msgid ""
"Direct import of driver %(name)r is deprecated as of Liberty in favor of its "
"entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"Direct import of driver %(name)r is deprecated as of Liberty, in favour of "
"its entrypoint from %(namespace)r and may be removed in N."

#: keystone/common/tokenless_auth.py:73
msgid "Neither Project Domain ID nor Project Domain Name was provided."
msgstr "Neither Project Domain ID nor Project Domain Name was provided."

#: keystone/common/tokenless_auth.py:165
msgid ""
"User auth cannot be built due to missing either user id, or user name with "
"domain id, or user name with domain name."
msgstr ""
"User auth cannot be built due to missing either user id, or user name with "
"domain id, or user name with domain name."

#: keystone/common/utils.py:63
msgid ""
"Length of transformable resource id > 64, which is max allowed characters"
msgstr ""
"Length of transformable resource id > 64, which is max allowed characters"

#: keystone/common/utils.py:192 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr "Invalid blob in credential"

#: keystone/common/wsgi.py:208
msgid "Query string is not UTF-8 encoded"
msgstr "Query string is not UTF-8 encoded"

#: keystone/common/wsgi.py:341
#, python-format
msgid "%s field is required and cannot be empty"
msgstr "%s field is required and cannot be empty"

#: keystone/common/wsgi.py:353
#, python-format
msgid "%s field(s) cannot be empty"
msgstr "%s field(s) cannot be empty"

#: keystone/common/wsgi.py:548
msgid "The resource could not be found."
msgstr "The resource could not be found."

#: keystone/common/kvs/core.py:88
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr "Lock Timeout occurred for key, %(target)s"

#: keystone/common/kvs/core.py:123
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr "KVS region %s is already configured. Cannot reconfigure."

#: keystone/common/kvs/core.py:166
#, python-format
msgid "Key Value Store not configured: %s"
msgstr "Key Value Store not configured: %s"

#: keystone/common/kvs/core.py:219
msgid "`key_mangler` option must be a function reference"
msgstr "`key_mangler` option must be a function reference"

#: keystone/common/kvs/core.py:376
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr "Lock key must match target key: %(lock)s != %(target)s"

#: keystone/common/kvs/core.py:380
msgid "Must be called within an active lock context."
msgstr "Must be called within an active lock context."

#: keystone/common/kvs/backends/memcached.py:68
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr "Maximum lock attempts on %s occurred."

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"
msgstr ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"

#: keystone/common/kvs/backends/memcached.py:185
msgid "`key_mangler` functions must be callable."
msgstr "`key_mangler` functions must be callable."

#: keystone/common/ldap/core.py:199
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"

#: keystone/common/ldap/core.py:209
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"

#: keystone/common/ldap/core.py:221
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"

#: keystone/common/ldap/core.py:591
msgid "Invalid TLS / LDAPS combination"
msgstr "Invalid TLS / LDAPS combination"

#: keystone/common/ldap/core.py:596
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr "Invalid LDAP TLS_AVAIL option: %s. TLS not available"

#: keystone/common/ldap/core.py:606
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr "tls_cacertfile %s not found or is not a file"

#: keystone/common/ldap/core.py:618
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr "tls_cacertdir %s not found or is not a directory"

#: keystone/common/ldap/core.py:1333
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr "ID attribute %(id_attr)s not found in LDAP object %(dn)s"

#: keystone/common/ldap/core.py:1378
#, python-format
msgid "LDAP %s create"
msgstr "LDAP %s create"

#: keystone/common/ldap/core.py:1383
#, python-format
msgid "LDAP %s update"
msgstr "LDAP %s update"

#: keystone/common/ldap/core.py:1388
#, python-format
msgid "LDAP %s delete"
msgstr "LDAP %s delete"

#: keystone/common/ldap/core.py:1400
#, python-format
msgid "Duplicate name, %s."
msgstr "Duplicate name, %s."

#: keystone/common/ldap/core.py:1557
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by configuration."
msgstr ""
"Disabling an entity where the 'enable' attribute is ignored by configuration."

#: keystone/common/ldap/core.py:1568
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr "Cannot change %(option_name)s %(attr)s"

#: keystone/common/ldap/core.py:1655
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr "Member %(member)s is already a member of group %(group)s"

#: keystone/common/sql/core.py:413
msgid "Duplicate Entry"
msgstr "Duplicate Entry"

#: keystone/common/sql/core.py:429
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr "An unexpected error occurred when trying to store %s"

#: keystone/common/sql/migration_helpers.py:167
msgid "Unable to downgrade schema"
msgstr "Unable to downgrade schema"

#: keystone/common/sql/migration_helpers.py:185
#: keystone/common/sql/migration_helpers.py:231
#, python-format
msgid "%s extension does not exist."
msgstr "%s extension does not exist."

#: keystone/common/validation/__init__.py:44
#, python-format
msgid ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."
msgstr ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."

#: keystone/common/validation/validators.py:53
#, python-format
msgid "Invalid input for field '%(path)s': %(message)s"
msgstr "Invalid input for field '%(path)s': %(message)s"

#: keystone/contrib/admin_crud/core.py:28
msgid ""
"Remove admin_crud_extension from the paste pipeline, the admin_crud "
"extension is now always available. Updatethe [pipeline:admin_api] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Remove admin_crud_extension from the paste pipeline, the admin_crud "
"extension is now always available. Update the [pipeline:admin_api] section "
"in keystone-paste.ini accordingly, as it will be removed in the O release."

#: keystone/contrib/ec2/controllers.py:80 keystone/contrib/s3/core.py:111
#: keystone/contrib/s3/core.py:114
msgid "Invalid EC2 signature."
msgstr "Invalid EC2 signature."

#: keystone/contrib/ec2/controllers.py:83
#: keystone/contrib/ec2/controllers.py:87
#: keystone/contrib/ec2/controllers.py:125
msgid "EC2 signature not supplied."
msgstr "EC2 signature not supplied."

#: keystone/contrib/ec2/controllers.py:159
msgid "User not valid for tenant."
msgstr "User not valid for tenant."

#: keystone/contrib/ec2/controllers.py:260
msgid "EC2 access key not found."
msgstr "EC2 access key not found."

#: keystone/contrib/ec2/controllers.py:326
msgid "Token belongs to another user"
msgstr "Token belongs to another user"

#: keystone/contrib/ec2/controllers.py:354
msgid "Credential belongs to another user"
msgstr "Credential belongs to another user"

#: keystone/contrib/endpoint_filter/routers.py:29
msgid ""
"Remove endpoint_filter_extension from the paste pipeline, the endpoint "
"filter extension is now always available. Update the [pipeline:api_v3] "
"section in keystone-paste.ini accordingly as it will be removed in the O "
"release."
msgstr ""
"Remove endpoint_filter_extension from the paste pipeline, the endpoint "
"filter extension is now always available. Update the [pipeline:api_v3] "
"section in keystone-paste.ini accordingly as it will be removed in the O "
"release."

#: keystone/contrib/federation/routers.py:27
msgid ""
"Remove federation_extension from the paste pipeline, the federation "
"extension is now always available. Update the [pipeline:api_v3] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Remove federation_extension from the paste pipeline, the federation "
"extension is now always available. Update the [pipeline:api_v3] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."

#: keystone/contrib/oauth1/routers.py:29
msgid ""
"Remove oauth1_extension from the paste pipeline, the oauth1 extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Remove oauth1_extension from the paste pipeline, the oauth1 extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."

#: keystone/contrib/revoke/routers.py:27
msgid ""
"Remove revoke_extension from the paste pipeline, the revoke extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Remove revoke_extension from the paste pipeline, the revoke extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."

#: keystone/contrib/s3/core.py:82
msgid "Credential signature mismatch"
msgstr "Credential signature mismatch"

#: keystone/contrib/simple_cert/routers.py:27
msgid ""
"Remove simple_cert from the paste pipeline, the PKI and PKIz token providers "
"are now deprecated and simple_cert was only used insupport of these token "
"providers. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Remove simple_cert from the paste pipeline, the PKI and PKIz token providers "
"are now deprecated and simple_cert was only used insupport of these token "
"providers. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."

#: keystone/contrib/user_crud/core.py:28
msgid ""
"Remove user_crud_extension from the paste pipeline, the user_crud extension "
"is now always available. Updatethe [pipeline:public_api] section in keystone-"
"paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Remove user_crud_extension from the paste pipeline, the user_crud extension "
"is now always available. Update the [pipeline:public_api] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."

#: keystone/endpoint_policy/core.py:264
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr "No policy is associated with endpoint %(endpoint_id)s."

#: keystone/federation/controllers.py:269
msgid "Request must have an origin query parameter"
msgstr "Request must have an origin query parameter"

#: keystone/federation/controllers.py:278
#, python-format
msgid "%(host)s is not a trusted dashboard host"
msgstr "%(host)s is not a trusted dashboard host"

#: keystone/federation/controllers.py:309
msgid "Missing entity ID from environment"
msgstr "Missing entity ID from environment"

#: keystone/federation/controllers.py:357
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr ""
"Use a project scoped token when attempting to create a SAML assertion"

#: keystone/federation/idp.py:486
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr "Cannot open certificate %(cert_file)s. Reason: %(reason)s"

#: keystone/federation/idp.py:552
msgid "Ensure configuration option idp_entity_id is set."
msgstr "Ensure configuration option idp_entity_id is set."

#: keystone/federation/idp.py:555
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr "Ensure configuration option idp_sso_endpoint is set."

#: keystone/federation/idp.py:574
msgid ""
"idp_contact_type must be one of: [technical, other, support, administrative "
"or billing."
msgstr ""
"idp_contact_type must be one of: [technical, other, support, administrative "
"or billing."

#: keystone/federation/utils.py:234
msgid "Federation token is expired"
msgstr "Federation token is expired"

#: keystone/federation/utils.py:286
msgid "Could not find Identity Provider identifier in environment"
msgstr "Could not find Identity Provider identifier in environment"

#: keystone/federation/utils.py:290
msgid ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."
msgstr ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."

#: keystone/federation/utils.py:585
#, python-format
msgid "User type %s not supported"
msgstr "User type %s not supported"

#: keystone/federation/utils.py:605
msgid ""
"Could not map any federated user properties to identity values. Check debug "
"logs or the mapping used for additional details."
msgstr ""
"Could not map any federated user properties to identity values. Check debug "
"logs or the mapping used for additional details."

#: keystone/federation/utils.py:629
#, python-format
msgid ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords must "
"be specified."
msgstr ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords must "
"be specified."

#: keystone/federation/utils.py:854
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr "Identity Provider %(idp)s is disabled"

#: keystone/federation/utils.py:862
#, python-format
msgid "Service Provider %(sp)s is disabled"
msgstr "Service Provider %(sp)s is disabled"

#: keystone/federation/backends/sql.py:182
#, python-format
msgid "Duplicate remote ID: %s"
msgstr "Duplicate remote ID: %s"

#: keystone/federation/backends/sql.py:184
#, python-format
msgid "Duplicate entry: %s"
msgstr "Duplicate entry: %s"

#: keystone/identity/controllers.py:74
msgid "Enabled field must be a boolean"
msgstr "Enabled field must be a boolean"

#: keystone/identity/controllers.py:103
msgid "Enabled field should be a boolean"
msgstr "Enabled field should be a boolean"

#: keystone/identity/core.py:265
#, python-format
msgid "Config API entity at /domains/%s/config"
msgstr "Config API entity at /domains/%s/config"

#: keystone/identity/core.py:271
#, python-format
msgid ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, the "
"last domain that appears to have had it is %(last_domain)s, giving up"
msgstr ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, the "
"last domain that appears to have had it is %(last_domain)s, giving up"

#: keystone/identity/core.py:450 keystone/identity/backends/ldap.py:62
#: keystone/identity/backends/ldap.py:64 keystone/identity/backends/ldap.py:70
#: keystone/identity/backends/ldap.py:72 keystone/identity/backends/sql.py:210
#: keystone/identity/backends/sql.py:212
msgid "Invalid user / password"
msgstr "Invalid user / password"

#: keystone/identity/core.py:895
#, python-format
msgid "User is disabled: %s"
msgstr "User is disabled: %s"

#: keystone/identity/core.py:928 keystone/resource/core.py:375
msgid ""
"update of domain_id is deprecated as of Mitaka and will be removed in O."
msgstr ""
"update of domain_id is deprecated as of Mitaka and will be removed in O."

#: keystone/identity/core.py:947
msgid "Cannot change user ID"
msgstr "Cannot change user ID"

#: keystone/identity/backends/ldap.py:35
#, python-format
msgid ""
"%s for the LDAP identity backend has been deprecated in the Mitaka release "
"in favor of read-only identity LDAP access. It will be removed in the \"O\" "
"release."
msgstr ""
"%s for the LDAP identity backend has been deprecated in the Mitaka release "
"in favour of read-only identity LDAP access. It will be removed in the \"O\" "
"release."

#: keystone/identity/backends/ldap.py:106
msgid "Cannot change user name"
msgstr "Cannot change user name"

#: keystone/identity/backends/ldap.py:214 keystone/identity/backends/sql.py:292
#: keystone/identity/backends/sql.py:310
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr "User '%(user_id)s' not found in group '%(group_id)s'"

#: keystone/identity/backends/ldap.py:366
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr "User %(user_id)s is already a member of group %(group_id)s"

#: keystone/models/token_model.py:62
msgid "Found invalid token: scoped to both project and domain."
msgstr "Found invalid token: scoped to both project and domain."

#: keystone/oauth1/controllers.py:126
msgid "Cannot list request tokens with a token issued via delegation."
msgstr "Cannot list request tokens with a token issued via delegation."

#: keystone/oauth1/controllers.py:187 keystone/oauth1/backends/sql.py:256
msgid "User IDs do not match"
msgstr "User IDs do not match"

#: keystone/oauth1/controllers.py:243
msgid "Invalid signature"
msgstr "Invalid signature"

#: keystone/oauth1/controllers.py:294 keystone/oauth1/controllers.py:372
msgid "Request token is expired"
msgstr "Request token is expired"

#: keystone/oauth1/controllers.py:308
msgid "There should not be any non-oauth parameters"
msgstr "There should not be any non-oauth parameters"

#: keystone/oauth1/controllers.py:312
msgid "provided consumer key does not match stored consumer key"
msgstr "provided consumer key does not match stored consumer key"

#: keystone/oauth1/controllers.py:316
msgid "provided verifier does not match stored verifier"
msgstr "provided verifier does not match stored verifier"

#: keystone/oauth1/controllers.py:320
msgid "provided request key does not match stored request key"
msgstr "provided request key does not match stored request key"

#: keystone/oauth1/controllers.py:324
msgid "Request Token does not have an authorizing user id"
msgstr "Request Token does not have an authorising user id"

#: keystone/oauth1/controllers.py:361
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr "Cannot authorise a request token with a token issued via delegation."

#: keystone/oauth1/controllers.py:388
msgid "authorizing user does not have role required"
msgstr "authorising user does not have role required"

#: keystone/oauth1/controllers.py:401
msgid "User is not a member of the requested project"
msgstr "User is not a member of the requested project"

#: keystone/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr "Consumer not found"

#: keystone/oauth1/backends/sql.py:177
msgid "Request token not found"
msgstr "Request token not found"

#: keystone/oauth1/backends/sql.py:237
msgid "Access token not found"
msgstr "Access token not found"

#: keystone/resource/controllers.py:94
msgid "The creation of projects acting as domains is not allowed in v2."
msgstr "The creation of projects acting as domains is not allowed in v2."

#: keystone/resource/controllers.py:284
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same time."
msgstr ""
"Cannot use parents_as_list and parents_as_ids query params at the same time."

#: keystone/resource/controllers.py:290
msgid ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same time."
msgstr ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same time."

#: keystone/resource/core.py:106
#, python-format
msgid "Max hierarchy depth reached for %s branch."
msgstr "Max hierarchy depth reached for %s branch."

#: keystone/resource/core.py:123
msgid "Multiple domains are not supported"
msgstr "Multiple domains are not supported"

#: keystone/resource/core.py:129
msgid "only root projects are allowed to act as domains."
msgstr "only root projects are allowed to act as domains."

#: keystone/resource/core.py:152
#, python-format
msgid ""
"Cannot create project, since its parent (%(domain_id)s) is acting as a "
"domain, but project's specified parent_id (%(parent_id)s) does not match "
"this domain_id."
msgstr ""
"Cannot create project, since its parent (%(domain_id)s) is acting as a "
"domain, but project's specified parent_id (%(parent_id)s) does not match "
"this domain_id."

#: keystone/resource/core.py:163
#, python-format
msgid ""
"Cannot create project, since it specifies its owner as domain %(domain_id)s, "
"but specifies a parent in a different domain (%(parent_domain_id)s)."
msgstr ""
"Cannot create project, since it specifies its owner as domain %(domain_id)s, "
"but specifies a parent in a different domain (%(parent_domain_id)s)."

#: keystone/resource/core.py:183
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr ""
"cannot create a project in a branch containing a disabled project: %s"

#: keystone/resource/core.py:191
#, python-format
msgid ""
"%(entity)s name cannot contain the following reserved characters: %(chars)s"
msgstr ""
"%(entity)s name cannot contain the following reserved characters: %(chars)s"

#: keystone/resource/core.py:201
#, python-format
msgid ""
"it is not permitted to have two projects acting as domains with the same "
"name: %s"
msgstr ""
"it is not permitted to have two projects acting as domains with the same "
"name: %s"

#: keystone/resource/core.py:205
#, python-format
msgid ""
"it is not permitted to have two projects with the same name in the same "
"domain : %s"
msgstr ""
"it is not permitted to have two projects with the same name in the same "
"domain : %s"

#: keystone/resource/core.py:262
#, python-format
msgid "Domain is disabled: %s"
msgstr "Domain is disabled: %s"

#: keystone/resource/core.py:279
#, python-format
msgid "Domain cannot be named %s"
msgstr "Domain cannot be named %s"

#: keystone/resource/core.py:282
#, python-format
msgid "Domain cannot have ID %s"
msgstr "Domain cannot have ID %s"

#: keystone/resource/core.py:297
#, python-format
msgid "Project is disabled: %s"
msgstr "Project is disabled: %s"

#: keystone/resource/core.py:304
#, python-format
msgid "Cannot enable project %s since it has disabled parents"
msgstr "Cannot enable project %s since it has disabled parents"

#: keystone/resource/core.py:340
msgid "Update of `parent_id` is not allowed."
msgstr "Update of `parent_id` is not allowed."

#: keystone/resource/core.py:345
msgid "Update of `is_domain` is not allowed."
msgstr "Update of `is_domain` is not allowed."

#: keystone/resource/core.py:359
msgid "Update of domain_id of projects acting as domains is not allowed."
msgstr "Update of domain_id of projects acting as domains is not allowed."

#: keystone/resource/core.py:366
msgid "Update of domain_id is only allowed for root projects."
msgstr "Update of domain_id is only allowed for root projects."

#: keystone/resource/core.py:371
msgid "Cannot update domain_id of a project that has children."
msgstr "Cannot update domain_id of a project that has children."

#: keystone/resource/core.py:396
#, python-format
msgid ""
"Cannot disable project %(project_id)s since its subtree contains enabled "
"projects."
msgstr ""
"Cannot disable project %(project_id)s since its subtree contains enabled "
"projects."

#: keystone/resource/core.py:443
msgid "Cascade update is only allowed for enabled attribute."
msgstr "Cascade update is only allowed for enabled attribute."

#: keystone/resource/core.py:507
#, python-format
msgid ""
"cannot delete an enabled project acting as a domain. Please disable the "
"project %s first."
msgstr ""
"cannot delete an enabled project acting as a domain. Please disable the "
"project %s first."

#: keystone/resource/core.py:513
#, python-format
msgid ""
"Cannot delete the project %s since it is not a leaf in the hierarchy. Use "
"the cascade option if you want to delete a whole subtree."
msgstr ""
"Cannot delete the project %s since it is not a leaf in the hierarchy. Use "
"the cascade option if you want to delete a whole subtree."

#: keystone/resource/core.py:526
#, python-format
msgid ""
"Cannot delete project %(project_id)s since its subtree contains enabled "
"projects."
msgstr ""
"Cannot delete project %(project_id)s since its subtree contains enabled "
"projects."

#: keystone/resource/core.py:554
msgid "Project field is required and cannot be empty."
msgstr "Project field is required and cannot be empty."

#: keystone/resource/core.py:795
msgid "Cannot delete a domain that is enabled, please disable it first."
msgstr "Cannot delete a domain that is enabled, please disable it first."

#: keystone/resource/core.py:1570
msgid "No options specified"
msgstr "No options specified"

#: keystone/resource/core.py:1576
#, python-format
msgid ""
"The value of group %(group)s specified in the config should be a dictionary "
"of options"
msgstr ""
"The value of group %(group)s specified in the config should be a dictionary "
"of options"

#: keystone/resource/core.py:1600
#, python-format
msgid ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"
msgstr ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"

#: keystone/resource/core.py:1607
#, python-format
msgid "Group %(group)s is not supported for domain specific configurations"
msgstr "Group %(group)s is not supported for domain specific configurations"

#: keystone/resource/core.py:1614
#, python-format
msgid ""
"Option %(option)s in group %(group)s is not supported for domain specific "
"configurations"
msgstr ""
"Option %(option)s in group %(group)s is not supported for domain specific "
"configurations"

#: keystone/resource/core.py:1666
msgid "An unexpected error occurred when retrieving domain configs"
msgstr "An unexpected error occurred when retrieving domain configs"

#: keystone/resource/core.py:1745 keystone/resource/core.py:1828
#: keystone/resource/core.py:1898 keystone/resource/config_backends/sql.py:76
#, python-format
msgid "option %(option)s in group %(group)s"
msgstr "option %(option)s in group %(group)s"

#: keystone/resource/core.py:1748 keystone/resource/core.py:1833
#: keystone/resource/core.py:1894
#, python-format
msgid "group %(group)s"
msgstr "group %(group)s"

#: keystone/resource/core.py:1750
msgid "any options"
msgstr "any options"

#: keystone/resource/core.py:1793
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"
msgstr ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"

#: keystone/resource/core.py:1798
#, python-format
msgid ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"
msgstr ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"

#: keystone/resource/core.py:1807
#, python-format
msgid ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"
msgstr ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"

#: keystone/resource/core.py:1814
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, but config provided "
"contains option %(option_other)s instead"
msgstr ""
"Trying to update option %(option)s in group %(group)s, but config provided "
"contains option %(option_other)s instead"

#: keystone/resource/core.py:2006
#, python-format
msgid "Group  %s not found in config"
msgstr "Group  %s not found in config"

#: keystone/resource/core.py:2016
#, python-format
msgid ""
"Reading the default for option %(option)s in group %(group)s is not supported"
msgstr ""
"Reading the default for option %(option)s in group %(group)s is not supported"

#: keystone/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr "invalid date format %s"

#: keystone/revoke/core.py:156
msgid ""
"The revoke call must not have both domain_id and project_id. This is a bug "
"in the Keystone server. The current request is aborted."
msgstr ""
"The revoke call must not have both domain_id and project_id. This is a bug "
"in the Keystone server. The current request is aborted."

#: keystone/revoke/core.py:226 keystone/token/provider.py:217
#: keystone/token/provider.py:256 keystone/token/provider.py:336
#: keystone/token/provider.py:343
msgid "Failed to validate token"
msgstr "Failed to validate token"

#: keystone/token/controllers.py:372
msgid "Tenant name cannot contain reserved characters."
msgstr "Tenant name cannot contain reserved characters."

#: keystone/token/controllers.py:392
#, python-format
msgid "Project ID not found: %(t_id)s"
msgstr "Project ID not found: %(t_id)s"

#: keystone/token/controllers.py:396
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr "User %(u_id)s is unauthorised for tenant %(t_id)s"

#: keystone/token/controllers.py:415 keystone/token/controllers.py:418
msgid "Token does not belong to specified tenant."
msgstr "Token does not belong to specified tenant."

#: keystone/token/provider.py:269 keystone/token/provider.py:293
msgid "No token in the request"
msgstr "No token in the request"

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr "Unknown token version %s"

#: keystone/token/providers/common.py:313
#: keystone/token/providers/common.py:445
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr "User %(user_id)s has no access to project %(project_id)s"

#: keystone/token/providers/common.py:318
#: keystone/token/providers/common.py:450
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr "User %(user_id)s has no access to domain %(domain_id)s"

#: keystone/token/providers/common.py:345
msgid "Trustor is disabled."
msgstr "Trustor is disabled."

#: keystone/token/providers/common.py:434
msgid "Trustee has no delegated roles."
msgstr "Trustee has no delegated roles."

#: keystone/token/providers/common.py:496
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr "Invalid audit info data type: %(data)s (%(type)s)"

#: keystone/token/providers/common.py:560
#: keystone/token/providers/common.py:587
msgid "The configured token provider does not support bind authentication."
msgstr "The configured token provider does not support bind authentication."

#: keystone/token/providers/common.py:598
msgid "User is not a trustee."
msgstr "User is not a trustee."

#: keystone/token/providers/common.py:665
msgid ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"
msgstr ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"

#: keystone/token/providers/common.py:675
msgid "Non-default domain is not supported"
msgstr "Non-default domain is not supported"

#: keystone/token/providers/common.py:679
msgid "Domain scoped token is not supported"
msgstr "Domain scoped token is not supported"

#: keystone/token/providers/pki.py:53 keystone/token/providers/pkiz.py:31
msgid "Unable to sign token."
msgstr "Unable to sign token."

#: keystone/token/providers/fernet/token_formatters.py:102
#, python-format
msgid "This is not a recognized Fernet token %s"
msgstr "This is not a recognised Fernet token %s"

#: keystone/token/providers/fernet/token_formatters.py:198
#, python-format
msgid "This is not a recognized Fernet payload version: %s"
msgstr "This is not a recognised Fernet payload version: %s"

#: keystone/trust/controllers.py:107
#, python-format
msgid "role %s is not defined"
msgstr "role %s is not defined"

#: keystone/trust/controllers.py:131
msgid "Redelegation allowed for delegated by trust only"
msgstr "Redelegation allowed for delegated by trust only"

#: keystone/trust/controllers.py:164
msgid "The authenticated user should match the trustor."
msgstr "The authenticated user should match the trustor."

#: keystone/trust/controllers.py:169
msgid "At least one role should be specified."
msgstr "At least one role should be specified."

#: keystone/trust/core.py:58
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed range "
"of [0..%(max_count)d]"
msgstr ""
"Remaining re-delegation depth of %(redelegation_depth)d out of allowed range "
"of [0..%(max_count)d]"

#: keystone/trust/core.py:67
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"

#: keystone/trust/core.py:78
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr "Requested expiration time is more than redelegated trust can provide"

#: keystone/trust/core.py:88
msgid "Some of requested roles are not in redelegated trust"
msgstr "Some of requested roles are not in redelegated trust"

#: keystone/trust/core.py:112
msgid "One of the trust agents is disabled or deleted"
msgstr "One of the trust agents is disabled or deleted"

#: keystone/trust/core.py:131
msgid "remaining_uses must be a positive integer or null."
msgstr "remaining_uses must be a positive integer or null."

#: keystone/trust/core.py:137
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than allowed "
"%(max_count)d"
msgstr ""
"Requested redelegation depth of %(requested_count)d is greater than allowed "
"%(max_count)d"

#: keystone/trust/core.py:144
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr "remaining_uses must not be set if redelegation is allowed"

#: keystone/trust/core.py:154
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting "
"this parameter is advised."
msgstr ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting "
"this parameter is advised."
